### ISSUE TITLE
Valid Point needs a measurement name and at least one field

### ISSUE THREAD

**Issue by JRusmir** [influxdata/influxdb-client-js#1055]
### Specifications

* Client Version: latest (1.35.0)
* InfluxDB Version: -
* Platform: nodejs

### Code sample to reproduce problem

```javascript

//...
try {
    const point = new Point('test')
        .tag('test-tag', 'test')
        .tag('test-tag2', 'test2')
        .timestamp(new Date());

    writeApi.writePoint(point);
    await writeApi.close();
} catch (error) {
    console.log('Error:', error);
}

//...
```

### Expected behavior

An error like "Your Point is invalid, for valid point you need measurement name and at least a field" or that the Point requires measurement name and a field.

### Actual behavior

The method of Point:toLineProtocol(settings?: Partial<PointSettings>)
return undefined for:

if (!this.name) return undefined

 if (fieldsLine.length === 0) return undefined // no fields present
 
 and WriteApiImpl ignores this point, no error no connection to influxdb.
 https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/impl/WriteApiImpl.ts#L303

### Additional info

Feel free to move it to "Feature request" if it is not fit your bug specification.

**Comment by bednar** [comment]
Hi @JRusmir,

Thank you for using our client and for your feedback on the `WriteApi` functionality.

The current design of the `WriteApi` intentionally ignores invalid points to ensure that the maximum number of valid points are written to the database. This approach is aimed at maintaining performance and data throughput, especially when dealing with large batches of data. If invalid points were to trigger an error, it could potentially require dropping an entire batch, which might not be desirable in many use cases.

Are you interested in helping us enhance this feature? All Pull Requests are welcome, and we are here to support you through the contribution process.

Please let me know if you would like to discuss this further or need any specific information to get started. We look forward to possibly collaborating with you on this improvement.

Best Regards
