### ISSUE TITLE
Add /api/v2 to the basepath

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/influxdb-client-js#124]
Currently the basepath for the URL used to contact InfluxDB v2 is missing /api/v2.

We should standardize how this is done across ALL client libs. @goller

**Comment by THPubs** [comment]
Either add it to the library or mention it in the Readme file.

**Comment by sranka** [comment]
This client library was replaced with a new version 20+ days ago. '/api/v2' is not used.
