### ISSUE TITLE
Write error: "XMLHtttpRequest is not defined"

### ISSUE THREAD

**Issue by tim-codes** [influxdata/influxdb-client-js#140]
Hi there, having a go with influx with some streaming data. JS client is throwing this error on client.write(). Running node `v12.4.0`.

`ReferenceError: XMLHttpRequest is not defined
    at data (/Users/tim/dev/personal/trading/trading-service/node_modules/@influxdata/influx/node_modules/axios/lib/adapters/xhr.js:12:30)
    at new Promise (<anonymous>)
    at Ie (/Users/tim/dev/personal/trading/trading-service/node_modules/@influxdata/influx/node_modules/axios/lib/helpers/cookies.js:49:15)
    at Te (/Users/tim/dev/personal/trading/trading-service/node_modules/@influxdata/influx/node_modules/axios/lib/core/dispatchRequest.js:51:55)`

Thanks in advance for any support.

**Comment by puncsky** [comment]
it does not make sense that your website says it's js/node library but it is actually just for browser... 

<img width="311" alt="Screen Shot 2019-11-07 at 1 43 14 PM" src="https://user-images.githubusercontent.com/1387285/68430270-9c5e3b00-0164-11ea-9305-1d2049761ad9.png">

**Comment by andrewhao** [comment]
I'm having issues with this too.

**Comment by bednar** [comment]
> it does not make sense that your website says it's js/node library but it is actually just for browser...
> 
> <img alt="Screen Shot 2019-11-07 at 1 43 14 PM" width="311" src="https://user-images.githubusercontent.com/1387285/68430270-9c5e3b00-0164-11ea-9305-1d2049761ad9.png">
> 
> btw, your python example does not work as well...

Hi @puncsky, what does not work with python client?

regards

**Comment by newbdez33** [comment]
Any update ?

**Comment by TestMannequin** [comment]
Also having issues with this.

**Comment by TestMannequin** [comment]
Workaround...

influxurl = 'https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/write?org=myorg&bucket=testbucket'
 
axios.post(influxurl, linedata,{headers: {
              'Authorization': 'Token <token>',
              'Content-Type': 'text/plain'                
            }})
            .then((res) => {
              console.log(`statusCode: ${res.statusCode}`)
              console.log(res)
            })
            .catch((error) => {
              console.error(error)
            })

**Comment by andrewhao** [comment]
Thanks @TestMannequin - I've done the same thing (using the REST API) in this project:

https://github.com/andrewhao/thermonoto/blob/master/services/influx.js#L3-L33

I may look into extracting this into a helper package if others find this useful.

**Comment by AntouanK** [comment]
so the `@influxdata/influx` is not to be used at all with node? It's only meant for the browser?
( because in the README it mentions `Node 10.x or higher` )

What you are doing is direct HTTP calls, right? 
Which bypasses this library from what I understand.

**Comment by kylebjordahl** [comment]
For some queries, it appears that the library is making direct calls with `XMLHttpRequest` which is only available in the browser.

To pollyfill it for node, you can use the following:
`npm i xhr2`

at the top of your index/main file, inject `xhr2` into global like the browser would:
```
global['XMLHttpRequest'] = require('xhr2');
```

**I wouldn't count on this for production code, but as they say, it's a WIP for now. Hopefully the library will solve this for itself one day...**

**Comment by vaclavh** [comment]
Same problem here. @influxdata let us know please after it will be ready for NodeJS env.

**Comment by andrewhao** [comment]
I extracted a client out from a personal project - please consider it experimental and very much not ready for production - but feel free to check it out: https://github.com/andrewhao/isomorphic-influx

**Comment by ravz** [comment]
> For some queries, it appears that the library is making direct calls with `XMLHttpRequest` which is only available in the browser. (I'm looking at you... `queries.execute()`)
> 
> To pollyfill it for node, you can use the following:
> `npm i xhr2`
> 
> at the top of your index/main file, inject `xhr2` into global like the browser would:
> 
> ```
> global['XMLHttpRequest'] = require('xhr2');
> ```
> 
> **I wouldn't count on this for production code, but as they say, it's a WIP for now. Hopefully the library will solve this for itself one day...**

thanks for this workaround!

**Comment by sranka** [comment]
This client library was replaced with a new version 20+ days ago. Both node and browser are now supported, see https://github.com/influxdata/influxdb-client-js/tree/master/examples ,
