### ISSUE TITLE
TypeScript reference path problem when installed via npm.

### ISSUE THREAD

**Issue by aegggsehyun1994** [influxdata/influxdb-client-js#148]
I'm using this in Angular 8.

In the file `@influxdata/influx/dist/api/api.d.ts`,
the first line is: `<reference path="../src/api/custom.d.ts" />`
It should be: `<reference path="../../src/api/custom.d.ts" />`

**Comment by russorat** [comment]
@aegggsehyun1994 thanks! Would you be able to open a quick PR for this?

**Comment by aegggsehyun1994** [comment]
I did some investigation, and I found that this issue could be a bug in TypeScript.
Check this out: https://github.com/Microsoft/TypeScript/issues/27572
Though I can write a temporary fix with shell script that will run on npm install.
If you are fine, I can write a PR this way.

**Comment by hoorayimhelping** [comment]
@aegggsehyun1994 can you post shell script fix in a code block (\`\`\`) or a [gist](https://gist.github.com/) if a code block is too long?

can you post the steps you took to trigger this error? (assuming it's `yarn install` but the specifics are helpful for posterity.

Thanks!

**Comment by aegggsehyun1994** [comment]
I originally found this bug when I used Angular CLI with npm, but now I found that I can reproduce this bug in a blank npm project. Here are the steps:
```
npm init
npm i @influxdata/influx
echo "import { Client } from '@influxdata/influx';" > index.ts  
tsc index.js
```

This script will produce following error:
```
node_modules/@influxdata/influx/dist/api/api.d.ts:1:22 - error TS6053: File '/opt/bitnami/nginx/html/influx/node_modules/@influxdata/influx/dist/src/api/custom.d.ts' not found.

1 /// <reference path="../src/api/custom.d.ts" />
                       ~~~~~~~~~~~~~~~~~~~~~~
```

Before I do anything to fix this, I would like to reask to you if a shell script would be the best temporary fix, until the TypeScript bug is resolved.
How would you like this to be fixed?
I think one-liner  `sed` command would be enough though.

**Comment by vaclavh** [comment]
Same problem I have temporarily fixed by this `prebuild` project script:

1. Install shelljs `npm install shelljs --save-dev`
2. Create prebuild script `./scripts/prebuild.js` with this content 

``` 
const shell = require('shelljs');

shell.sed('-i', '../src/api/custom.d.ts', '../../src/api/custom.d.ts', './node_modules/@influxdata/influx/dist/api/api.d.ts');
 ```
3. Append to project's `package.json` scripts section:

```
"scripts": {
   ...
    "prebuild": "node ./scripts/prebuild.js",
   ...
```

**Comment by sranka** [comment]
This client library was replaced with a new version 20+ days ago, so this issue is outdated. Typescript definition files have changed.
