### ISSUE TITLE
Can i use the code in nodejs? It throw exception: Client is not a constructor

### ISSUE THREAD

**Issue by cettco** [influxdata/influxdb-client-js#151]
My nodejs verions is v13.7.0. I follow https://nodejs.org/api/esm.html document to support es6. but  when I run the code, like this :
import Client from '@influxdata/influx'
const client = new Client('basepath', 'token').

it throw exception: TypeError: Client is not a constructor.

How can I use it in nodejs?

**Comment by JoeRandom** [comment]
+1

**Comment by jeromewir** [comment]
Hey, just ran into this, you need to change the import line to:
```
import { Client } from '@influxdata/influx'
```

The client is not exported by default

**Comment by bednar** [comment]
Yes, see examples - https://github.com/influxdata/influxdb-client-js/tree/master/examples

**Comment by JoeRandom** [comment]
> Hey, just ran into this, you need to change the import line to:
> 
> ```
> import { Client } from '@influxdata/influx'
> ```
> 
> The client is not exported by default

Thank you very much for the clarification Jérôme.
