### ISSUE TITLE
Wrong module name on install instructions

### ISSUE THREAD

**Issue by codesxt** [influxdata/influxdb-client-js#154]
Last night I tried to install the client following instructions from the README.md file but it gave me a 404 error from npmjs. The instructions are:

`npm install --save @influxdata/influxdb-client`

Today I realized in another issue that it has to be installed this way:

`npm install --save @influxdata/influx`

I would have sent a PR for the README buy I'm not sure if the name is referenced somewhere else too (I'm just testing this library), so maybe someone with experience in the project could fix the name where required.

**Comment by russorat** [comment]
@codesxt thanks for opening this. We are in the process of publishing an updated version of this to npm since we just made some major changes to master. I'll make sure these docs get updated soon.

**Comment by HuMoran** [comment]
Waiting for your update

**Comment by russorat** [comment]
Look for an update in NPM soon. Thank you!

**Comment by russorat** [comment]
A new version was just pubblished: https://github.com/influxdata/influxdb-client-js/releases/tag/v1.0.0
