### ISSUE TITLE
experiencing cors issues

### ISSUE THREAD

**Issue by fmr999** [influxdata/influxdb-client-js#160]
## Expected Behavior

Connect to  influx db via react application to request a query to a bucket

## Current Behavior

Currently getting the following message on console:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://x.x.x.x:9999/api/v2/query?org=org. (Reason: expected ‘true’ in CORS header ‘Access-Control-Allow-Credentials’).

followed example 

## Possible Solution

would I need to configure something in influx, or modify request?

## Steps/Code to Reproduce the Problem

1. step1 - influx 2.0 is on VM A
1. step 2 - react application is on VM B

```
// ...
writeApi.writeRecord(...)
```

## Specifications

- Version: 2.0.0 (2295247)
- Platform: influx 2.0, react 16.12.0

**Comment by bednar** [comment]
Hi @fmr999,

thanks for using our client. 

The issue is fixed in milestone [1.2.0](https://github.com/influxdata/influxdb-client-js/milestone/11).

Regards

**Comment by gabrielmancini** [comment]
i need this release too, when this release will be out?

**Comment by bednar** [comment]
Hi @gabrielmancini,

The 1.2.0 will be released probably at 17 Apr 2020, but We will prepare a nightly build as soon as possible.

Regards

**Comment by sranka** [comment]
@gabrielmancini @fmr999 ... you can use the following code until the next version is released:

```js
      const influxDB = new InfluxDB({url, token})
      // WORKAROUND https://github.com/influxdata/influxdb-client-js/issues/160
      influxDB.transport.fetch = function (path/*: string */, body/*: any */, options/*: SendOptions */)/*: Promise<Response> */ {
        const {method, headers, ...other} = options
        return fetch(`${this.connectionOptions.url}${path}`, {
          method: method,
          body:
            method === 'GET' || method === 'HEAD'
              ? undefined
              : typeof body === 'string'
              ? body
              : JSON.stringify(body),
          headers: {
            ...this.defaultHeaders,
            ...headers,
          },
          credentials: 'omit' /* as 'omit' */,
          ...other,
        })
      }.bind(influxDB.transport)
```
