### ISSUE TITLE
are subscriptions supported here?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [influxdata/influxdb-client-js#163]
sorry can't find it
https://docs.influxdata.com/influxdb/v1.7/administration/subscription-management

I need an API server to subscribe to updates in the database and stream them using websockets.

Any recommendations?

**Comment by bednar** [comment]
Hi @hp8wvvvgnj6asjm7,

This library is for InfluxDB v2. Try to use [node-influx](https://github.com/node-influx/node-influx).

Regards

**Comment by hp8wvvvgnj6asjm7** [comment]
I am willing to use v2 too, if there is a functionality such as streaming / pushing updates from a database similar to subscriptions.

**Comment by bednar** [comment]
What about combination of `Task` and `http.endpoint`?

- https://v2.docs.influxdata.com/v2.0/process-data/manage-tasks/create-task/
- https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/http/endpoint/
