### ISSUE TITLE
writeApi.writeRecord() not working in the cloud

### ISSUE THREAD

**Issue by nmummau** [influxdata/influxdb-client-js#170]
## Expected Behavior
writeApi.writeRecord() is functional in the cloud.

## Current Behavior

writeApi.writeRecord() is not functional in the cloud.

## Steps/Code to Reproduce the Problem

1. Follow the docs listed in the client library dialog: https://us-central1-1.gcp.cloud2.influxdata.com/orgs/{organization}/load-data/client-libraries/javascript-node
2. Update the code to reference your bucketId, etc. 
BUG: `writeApi.writeRecord(data)` appears to work, but the data is never available in the bucket

My code looks like this
```
const writeApi = influxClient.getWriteApi('orgId', 'bucketId');
arrayOfData.forEach(d => {
    const data = `fed_weight value=${d.fedWeight} ${d.fedOn.getTime()}`; // Line protocol string
    writeApi.writeRecord(data);
    console.log('data', data);		
});
writeApi.close()
    .then(() => {
        console.log('FINISHED');
    });
````

`console.log('data', data); ` results in the following
```
data fed_weight value=8380 1584346763730
data fed_weight value=9720 1584294154693
```

## Other info
I did try the [Point method listed in this example](https://github.com/influxdata/influxdb-client-js/blob/master/examples/write.js) which seems to work. But I couldn't figure out how to send a timestamp along in that method so I'd like to use writeRecord.

## Specifications

- Version: Cloud 2.0
- Platform: Node.js.

**Comment by sranka** [comment]
Thank you for reporting this issue. Can you please also attach an example of what is printed with your:
```
console.log('data', data)
```

https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/Point.ts#L121 is the 
Point method that you were looking for. OOTB the time part is supplied in nanoseconds since epoch. You can switch to seconds, milliseconds or microseconds with the 3rd parameter when obtaining the WriteApi, such as: `influxClient.getWriteApi('orgId', 'bucketId','s')`

**Comment by nmummau** [comment]
@sranka I updated the original bug with the results of the console.log().

**Comment by sranka** [comment]
OK, d.fedOn.getTime() probably returns milliseconds, you should then obtain the write API using

```
const writeApi = influxClient.getWriteApi('orgId', 'bucketId','ms');
```

**Comment by nmummau** [comment]
Yes, I believe it does. As an example:
```
d.fedOn = 2020-03-15T17:42:34.693Z
d.fedOn.getTime() = 1584294154693
```

**Comment by nmummau** [comment]
`const writeApi = influxClient.getWriteApi('orgId', 'bucketId', 'ms'); ` results in an error in the type definition.
>Argument of type '"ms"' is not assignable to parameter of type 'WritePrecision | undefined'.ts(2345)

**Comment by sranka** [comment]
Yes ... depending on the environment, if you are in typescript, use `WritePrecision.ms`

**Comment by nmummau** [comment]
I just did that too
`const writeApi = influxClient.getWriteApi('org', 'bucket', WritePrecision.ms);`

Still nothing is visible in my bucket...

**Comment by nmummau** [comment]
It's definitely something to do with my timestamp. Because it's also not working when using the Point class.

This does work
```
const point1 = new InfluxDB.Point('fed_weight')
    .floatField('value', d.fedWeight)
    writeApi.writePoint(point1)
```

```
const point2 = new InfluxDB.Point('fed_weight')
    .timestamp(`${frb.fedOn.getTime()}`)
    .floatField('value', d.fedWeight)
    writeApi.writePoint(point2)
```

Note that with the Point() class, I'm not sure how to specify the WritePrecission of the timestamp.

**Comment by sranka** [comment]
```js
const writeApi = new InfluxDB({url, token}).getWriteApi(
  org,
  bucket,
  'ms' as WritePrecision
)
```
or use:
```js
.timestamp(`${d.fedOn.getTime()}000000000`)
```

**Comment by nmummau** [comment]
This silently fails and nothing makes it to my bucket.
```
const writeApi = new InfluxDB({url, token}).getWriteApi(
  org,
  bucket,
  'ms' as WritePrecision
)
```

This results in an error
```
.timestamp(`${d.fedOn.getTime()}000000`)
```

>400 Bad Request : {"code":"invalid","message":"unable to parse \'fed_weight value=1200 1586787459890000000\': time outside range -9223372036854775806 - 9223372036854775806', _retryAfter: 0 }

**Comment by sranka** [comment]
@nmummau the following code works fine for me:

```
#!./node_modules/.bin/ts-node

import {
  InfluxDB,
  Point,
  WritePrecision,
  FluxTableMetaData,
} from '@influxdata/influxdb-client'
const {url, token, org, bucket} = require('./env')

const measurement = 'test4'
const influxDB = new InfluxDB({url, token})

console.log('*** WRITE (default/ns precision) ***')
const point1 = new Point(measurement)
  .floatField('value', 8390)
  .timestamp(`${new Date(1584346763730).getTime()}000000`) // add '000000' to have nanoseconds
const writeApi1 = new InfluxDB({url, token}).getWriteApi(
  org,
  bucket /* ,
  'ns' as WritePrecision */
)
writeApi1.writePoint(point1)
writeApi1
  .close()
  .then(() => {
    console.log('FINISHED ns')
  })
  .catch((e: object) => {
    console.error(e)
  })

console.log('*** WRITE (ms precision) ***')
const writeApi2 = new InfluxDB({url, token}).getWriteApi(
  org,
  bucket,
  'ms' as WritePrecision
)
const point2 = new Point(measurement)
  .floatField('value', 9720)
  .timestamp(`${new Date(1584294154693).getTime()}`)
writeApi2.writePoint(point2)
writeApi2
  .close()
  .then(() => {
    console.log('FINISHED ms')
  })
  .catch((e: object) => {
    console.error(e)
  })

const query = function(): void {
  const queryApi = influxDB.getQueryApi(org)
  const fluxQuery = `from(bucket:"${bucket}") |> range(start: 0) |> filter(fn: (r) => r._measurement == "${measurement}")`

  console.log('*** QUERY ROWS ***')
  // performs query and receive line table metadata and rows
  // https://v2.docs.influxdata.com/v2.0/reference/syntax/annotated-csv/
  queryApi.queryRows(fluxQuery, {
    next(row: string[], tableMeta: FluxTableMetaData) {
      const o = tableMeta.toObject(row)
      console.log(JSON.stringify(o, null, 2))
    },
    error(error: Error) {
      console.error(error)
      console.log('\nFinished ERROR')
    },
    complete() {
      console.log('\nFinished SUCCESS')
    },
  })
}
// wait a second so that values are (for sure) persisted on the server side
setTimeout(query, 1000)
```

**Comment by nmummau** [comment]
I copy and pasted your code for the first test with `ns`. The writeApi1 does not work for me. If I comment out the timestamp 
```
//.timestamp(`${new Date(1584346763730).getTime()}000000`) // add '000000' to have nanoseconds
```
Then it works and I see it in my bucket.

But with .timestamp(), it does not work

**Comment by sranka** [comment]
A Point without a timestamp (undefined) is written with a timestamp of the client ( node.js application ) adjusted to WriteAPI's precision, this is probably not what you want.

"writeApi1 does not work for me" means that it fails on "time outside of range" or "no such data are returned when queried"?

A flux query that will include your `new Date(1584346763730)` can be adjusted to
```
const fluxQuery = `from(bucket:"${bucket}") |> range(start: 2020-03-16T08:19:23.73Z, stop: 2020-03-16T08:19:23.74Z ) |> filter(fn: (r) => r._measurement == "${measurement}")`
```

**Comment by nmummau** [comment]
I know that that isn't what I want. I really need to be able to provide my own timestamp... I was just pointing out that it _does_ work when I do not include a timestamp.

"writeApi1 does not work for me" means that it fails silently (appears as if it worked, no errors) but nothing makes it to my bucket. 

I'm not even trying to do a flux query at this point. I'm just trying to get the data into the bucket so I can see it in the UI. I'll worry about querying with flux later if I can actually get data into the bucket with valid timestamps.

**Comment by sranka** [comment]
@nmummau I was trying to point out that the timestamp of your data is 2020-03-16T08:19:23.73Z, the web UI's Data Explorer might show nothing depending on the time range selection of the UI, which might be only the last hour. We could avoid these "maybe"s with a specific flux query executed using the API and then move forward.

**Comment by nmummau** [comment]
@sranka  I want to thank you for going back and forth with me today. You pointing that out solved my issue. The UI hides "_measurements" unless they are eligible for the current time range. I didn't realize that, and I assumed that the absence of the measurement meant that the client library had an issue. User error on my part. 
![image](https://user-images.githubusercontent.com/10524529/79278985-f46b3d00-7e7a-11ea-841f-5a35e66c3cd4.png)


I apologize for wasting your time with this. Thanks again. Hopefully, if anything this prevents someone else from making the same mistake.
