### ISSUE TITLE
Links in doc comments

### ISSUE THREAD

**Issue by nmummau** [influxdata/influxdb-client-js#172]
## Expected Behavior
Typescript doc comments with links are clickable in VSCode.

## Current Behavior
Typescript doc comments display the link but it's not actually a link.

## Possible Solution

Update `@see` to be `@link`.
Update `<a href>` to be `@link`.

## Steps/Code to Reproduce the Problem
Implement the client library into a typescript project.
Hover your mouse over a type and see the issue in the link:
![image](https://user-images.githubusercontent.com/10524529/79264001-cb8a7e00-7e61-11ea-8d77-ec7938d49b62.png)

## Specifications

- Version: "@influxdata/influxdb-client": "^1.1.0",
- Typescript 3.8.3
- VSCode 1.44.0
- OS: Ubuntu 18.04.4

**Comment by nmummau** [comment]
I can create a PR to fix this, as long as the "@see" isn't being parsed in internal documentation tools or something.

**Comment by sranka** [comment]
Thank you @nmummau for the PR offer. There is a lot of code that is generated from API documentation (swagger), the generator will have to be repaired as well so that no manual changes get overwritten when re-generated. I will repair the generator and a few other links that you pointed out.
