### ISSUE TITLE
Expose WriteAPI Options in getWriteAPI

### ISSUE THREAD

**Issue by yarncraft** [influxdata/influxdb-client-js#184]
## Expected Behavior`

I would expect to be able to alter the buffer size and delay settings.

```
  getWriteApi(
    org: string,
    bucket: string,
    precision: WritePrecision = WritePrecision.ns
  ): WriteApi {
    return new WriteApiImpl(
      this.transport,
      org,
      bucket,
      precision,
      this._options.writeOptions
    )
  }
```

## Current Behavior
In the current setup, it is not possible to pass the options through the getWriteAPI.

## Possible Solution
Add the writeOptions as an optional parameter in the getWriteApi method and pass it to the constructor of WriteApiImpl when assigned.

**Comment by russorat** [comment]
@yarncraft thanks for opening! should be fixed with the attached PR!

**Comment by yarncraft** [comment]
Thank you!
