### ISSUE TITLE
Add ping method to check server status and version

### ISSUE THREAD

**Issue by coussej** [influxdata/influxdb-client-js#187]
The old client had a .Ping(timeout) method so you could check if the server was online. Was pretty useful :-)

**Comment by sranka** [comment]
Thank you @coussej for submitting an issue. 

There is no ping in 2.0 API, but there is `health` in InfluxDB 2.0. This API was also backported to 1.8. See [health.js](https://github.com/influxdata/influxdb-client-js/blob/master/examples/health.js) example.

The default timeout (for a node.js client) is 10 seconds, and you can set you own this way:
```
const timeout = 20000 // 20 seconds
const influxDB = new InfluxDB({url, token, timeout})
```
