### ISSUE TITLE
Include example to the website's Client Libraries example

### ISSUE THREAD

**Issue by angeloanan** [influxdata/influxdb-client-js#190]
This might not be the right place to give suggestion but

Please do include the updated library example (./examples) on the website, especially, the writing data example.

I have spend a considerable amount of time writing a "data to influx line protocol" function and wasn't aware that [Point](https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/Point.ts) existed to help data entry.

Including the updated example might save time for other developers trying out the library.

**Comment by sranka** [comment]
Thank you for reporting this issue. 
1. influxdata/influxdb#18313 uses Point 
2. The UI already informs that you should better check examples in this repo
![image](https://user-images.githubusercontent.com/16321466/83373698-8d253000-a3c9-11ea-86df-2b955d45bec3.png)
