### ISSUE TITLE
Include example for batch writing

### ISSUE THREAD

**Issue by chobbs** [influxdata/influxdb-client-js#192]
Suggest adding expanded get-started examples that show how to batch write points to InfluxDB:  **writePoints**()

**Comment by sranka** [comment]
Thank you for reporting this, the client's Write API always buffer points/lines to create batches
under the hood OOTB to optimize data transfer to InfluxDB server in all its write* functions. A user can flush all pending writes as shown in 

https://github.com/influxdata/influxdb-client-js/blob/master/examples/write.js#L29.

So I will add notes in examples/write.js in the main doc and improve WriteAPI doc to make this clear. Will it address your suggestion? @chobbs

**Comment by chobbs** [comment]
Yes , that is good.
