### ISSUE TITLE
Import for flux missing in @influxdata/influxdb-client

### ISSUE THREAD

**Issue by JBuijgers** [influxdata/influxdb-client-js#194]
## Expected Behavior
As per https://github.com/influxdata/influxdb-client-js/blob/master/examples/queryWithParams.ts#L9 I would expect being able to import flux and fluxDuration.

## Current Behavior
An error: Module ... has no exported member 'flux'

## Possible Solution
Export flux and fluxDuration or update the example if these exports do no exist anymore or are unneeded.

## Steps/Code to Reproduce the Problem
1. Run https://github.com/influxdata/influxdb-client-js/blob/master/examples/queryWithParams.ts
2. See error.

## Specifications
- Version: 1.3.0
- Platform: Linux, NodeJS 12

**Comment by JBuijgers** [comment]
This is strange though, looking at https://github.com/influxdata/influxdb-client-js/blob/4c407783555dc484da551642ff0a403fc3e31733/packages/core/src/query/index.ts#L7 I would say it is being exported. Upon further fiddling around, my code does compile, only the IDE is giving me this error. Weird, might be an IDE thing. Going to do some further testing.

**Comment by sranka** [comment]
The `flux` function will be available in 1.4.0 version of the client, see https://github.com/influxdata/influxdb-client-js/blob/master/CHANGELOG.md. 
You can either
   * See and reference sources for the latest stable version, switch to 1.3.0 tag https://github.com/influxdata/influxdb-client-js/tree/v1.3.0
   * Use a nightly build with the flux function, and update to 1.4.0 once it is released. We do releases every month or two. See versions in https://www.npmjs.com/package/@influxdata/influxdb-client for available nightly builds.
