### ISSUE TITLE
InfluxQL with Influx 1.8

### ISSUE THREAD

**Issue by Infern1** [influxdata/influxdb-client-js#195]
## Expected Behavior

If I define type `influxql` I should be able to do a simple query

## Current Behavior

Response with a bad request

`const queryApi = this.influxClient.getQueryApi('').with({ type: 'influxql' });`

Error log:

```
Error: 400 Bad Request : {"error":"unknown query type: influxql"}
WEB_TreCycWriter.ts:461
_retryAfter:0
body:"{"error":"unknown query type: influxql"}
"
message:"400 Bad Request : {"error":"unknown query type: influxql"}
"
stack:"Error: 400 Bad Request : {"error":"unknown query type: influxql"}

    at IncomingMessage.<anonymous> (D:\Public\WEB_InfluxDB\node_modules\@influxdata\influxdb-client\src\impl\node\NodeHttpTransport.ts:219:13)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
statusCode:400
statusMessage:"Bad Request"
```

## Possible Solution

Accept `influxql` since I want to do an easy query:
`SHOW DATABASES` since with 1.8 the `buckets()` doesn't work.

I can get a proper response by:
```typescript
    const queryApi = this.influxClient.getQueryApi('');

    //const query = `SHOW DATBASES`;
    const query = `
                import "influxdata/influxdb/v1"
                v1.databases()
                `;
    const databases = [];
    queryApi.queryRows(query, {
      next(row: string[]) {
        //const o = tableMeta.toObject(row);
        //console.log(`${o._time} ${o._measurement} : ${o._field}=${o._value}`);
        //databases = row.
        console.log(row);
      },
      error(error) {
        console.error(error);
      },
      complete() {
        console.log('\nFinished');
      },
```

## Steps/Code to Reproduce the Problem

1. Run Influx 1.8.0 and try to do InfluxQL query

## Specifications

- Version:
- Platform:

**Comment by sranka** [comment]
Thank you for reporting this issue and describing your workaround. 

InfluxDB1.8 server now does not support influxql queries in [2.0 compatibility endpoints](https://docs.influxdata.com/influxdb/v1.8/tools/api/#influxdb-2-0-api-compatibility-endpoints) that are used by this client, the [code](https://github.com/influxdata/influxdb/blob/master-1.x/flux/client/request.go#L62) accepts only flux queries.

The 2.0 documentation mentions only flux queries, even though the 2.0 API offers the influxql query option, the support of influxql in 2.0 is not documented, therefore it is not something to rely upon. Your query would fail also in 2.0:
```
$ curl -X POST -H "Authorization: Token ${INFLUX_TOKEN}" "${INFLUX_HOST}/api/v2/query?org=${INFLUX_ORG}" -d '{"type": "influxql", "query": "SHOW DATABASES", "bucket": "my-bucket"}'
// returns {"error":"interface conversion: interface {} is nil, not v1.DatabasesDependencies"}
```

The 2.0 API shall be used to post flux queries.I think that we should better remove the experimental `influxql` support from this client.

**Comment by Infern1** [comment]
Thanks for the clarification

> I would better remove the `influxql` option from this client, so that we will not confuse users that influxql is the way that could be used to query the DB through this client.

Yes I agree

The reason for trying this client is the statement:

> If you are just getting started with InfluxDB 1.x today, we recommend adopting the latest client libraries. They allow you to easily move from InfluxDB 1.x to InfluxDB 2.0 Cloud or open source, (when you are ready).

Since we already have an existing nodejs application using the current node-influx client I was thinking it would be nice to prepare our self for the new 2.0 series. Using the compatibility mode by using `influxql` this would mean we don't have to rewrite all queries at once and can do it step by step and compare the results easily.

I will put our migration on hold for now, since we are running Influx on Windows environment and at the moment there are no binaries for 2.0. So no (easy) adoption for the 2.0 with Influx.

Issue can be closed from my point of view.
