### ISSUE TITLE
error handling for writePoint/writePoints

### ISSUE THREAD

**Issue by cinhcet** [influxdata/influxdb-client-js#197]
## Expected Behavior
Add error handling for `writePoints` or `writePoint`

## Current Behavior
Calling `writePoints` or `writePoint` does return nothing. 
If an error occurs in the write after the flushInterval, an error is only logged to the console and not available for the rest of the program.

## Possible Solution
Fire an `writeError` or similar event if an error during a write occurs.

## Specifications
- Version: 1.3.0
- Platform: nodejs v12

**Comment by sranka** [comment]
Thank you @cinhcet for reporting this error. I am thinking about a new `writeFailed` option that could be supplied when creating the WriteApi. Something like:

```js
  /**
   * writeFailed is called to inform about write failure
   * @param source the instance of the API that failed
   * @param error write error
   * @param lines failed lines
   * @param attempts a number of failed attempts to write the lines
   * @return `true` forces the API to not retry again
   */
  writeFailed?: (
    source: WriteApi,
    error: Error,
    lines: Array<string>,
    attempts: number
  ) => boolean | void

```

**Comment by cinhcet** [comment]
such an `writeFailed` callback would do exactly what I need!

Thanks a lot, looking forward to it.

I actually like the retries and caching behavior, I just need to have a way of reacting to errors that might happen during a write.

**Comment by cinhcet** [comment]
thanks!!
