### ISSUE TITLE
why queryApi.queryRows not acts as Promise?

### ISSUE THREAD

**Issue by mogadanez** [influxdata/influxdb-client-js#198]
hard to use in standard flows  - require to make own wrappers etc

**Comment by sranka** [comment]
Thank you for reporting an issue. There can be a lot of results returned by the query, so we do not cache all results in memory, which you would have to do with a Promise. You can use a standard flow of Observables to stream the results, collect them, and convert to a promise.

**Comment by cailloumajor** [comment]
@mogadanez is your problem similar to #199 ?

**Comment by sranka** [comment]
#200 add new utility functions with warnings into QueryApi
