### ISSUE TITLE
Unable to use InfluxDB 1.8 directly from the browser

### ISSUE THREAD

**Issue by cailloumajor** [influxdata/influxdb-client-js#199]
### Background
I am developing a web application based on Vue.js (client-side) that needs to query InfluxDB 1.8 at regular interval, using Flux. The application reaches InfluxDB directly by `http://host:port`. I first tried to use this library (version `1.4.0-nightly.14`) as in [examples/influxdb-1.8.ts](https://github.com/influxdata/influxdb-client-js/blob/3fd906832b68316e171550736ab9f20db54aaad3/examples/influxdb-1.8.ts), but I couldn't make it work due to CORS preflight not acknowledged by InfluxDB (v1.8.0).
I then decided to use `@influxdata/influxdb-client-apis` (version `1.3.0`) to do the query (using `QueryAPI.postQuery`), with the code below:

(note the usage of `{ mode: "no-cors" }` as `postQuery`'s request options, intended for `fetch` call, and which raises a typing error)
```ts
import { flux, InfluxDB } from "@influxdata/influxdb-client"
import { QueryAPI } from "@influxdata/influxdb-client-apis"
import { Plugin } from "vuex"

import { automation } from "../modules/automation"

export default function createVuexPlugin(
  url: string,
  DBName: string
  // eslint-disable-next-line
): Plugin<any> {
  return store => {
    const ctx = automation.context(store)
    const influxDB = new InfluxDB({ url })
    const queryAPI = new QueryAPI(influxDB)
    const bucket = `${DBName}/autogen`
    const query = flux`\
      from(bucket: "${bucket}")
        |> range(start: -1d)
        |> increase()
        |> yield()`.toString()

    function influxQuery() {
      queryAPI
        .postQuery(
          { body: { query } },
          // eslint-disable-next-line
          // @ts-ignore
          { mode: "no-cors" }
        )
        .then((value: string) => console.log(value))
    }

    window.setInterval(influxQuery, 10000)
  }
}
```
The query now fulfills, but I receive an disappointing `undefined` string as the result of the succeeding Promise ! (see below the console of Firefox Developer Edition)
![image](https://user-images.githubusercontent.com/8583146/84028712-82eacf00-a991-11ea-8919-bcfa69c45a8e.png)

The response from InfluxDB seems to be conform:
![image](https://user-images.githubusercontent.com/8583146/84029139-348a0000-a992-11ea-85a0-b9bc0039ca13.png)

### Description of the problem
For a reason I don't understand, commit d106c08 made `Content-Type` header name all-lowercase (and I fear other cases like this were introduced later, eg. `accept-encoding` 1c9ba45), IMHO preventing them to being correctly interpreted by browsers and InfluxDB (see below, showing that `Content-Type: application/json` is not sent to InfluxDB, despite the intention in `QueryAPI.postQuery`).
![image](https://user-images.githubusercontent.com/8583146/84032148-2d192580-a997-11ea-8b98-bdc15e8d714e.png)
For the case described in this issue, this makes `responseContentType` below always equal to empty string, making the whole function return `undefined`.
https://github.com/influxdata/influxdb-client-js/blob/3fd906832b68316e171550736ab9f20db54aaad3/packages/core/src/impl/browser/FetchTransport.ts#L110-L135

### Additional thoughts
This issue makes me being in trouble, because it prevents the whole library from being usable in my use case, this one not being an edge case IMHO.
Does anyone have an idea about the CORS preflight problem described at the beginning ?
* Is it also due to this issue ?
* Is InfluxDB 1.x missing correct handling of CORS (as https://github.com/influxdata/influxdb/pull/17640 seems to be fixing for InfluxDB v2) ?

**Comment by sranka** [comment]
@cailloumajor the  [browser example](https://github.com/influxdata/influxdb-client-js/blob/master/examples/index.html) works fine when used against a proxy and it does not when using CORS now. The [server code]() in v1 does not handle CORS as v2 does, so it is blocked by the client. I am on the way to find a workaround.

**Comment by sranka** [comment]
I found out that CORS is not supported in "v2 compatibility endpoint" of InfluxDB v1, this is now reported in influxdata/influxdb#17640 .

There is no way to work around this, other than using a proxy that would satisfy CORS requirements or running a browser to ignore CORS requirements.

**Comment by sranka** [comment]
Regarding your workaround @cailloumajor . The "no-cors" mode allows only limited settings of content-type, "application/json" is not allowed ... that's why your FF sends text/plain. Additionally, in the 'no-cors' mode, fetch returns an [opaque response](https://fetch.spec.whatwg.org/#concept-filtered-response-opaque) with unrecognized content-type response header and even body would be null.

**Comment by cailloumajor** [comment]
@sranka thank you for those informations, and sorry for wrongly focusing on headers names case.

I am going to try using a proxy in my project, it was planned for production but it seems I need it in development too...

**Comment by sranka** [comment]
You are welcome, I will keep this open until influxdata/influxdb#18391 is fixed .

**Comment by jitendracodehacker** [comment]
@sranka : i am also facing the CORS issue when i use the example code in my browser.

**Comment by sranka** [comment]
Thank you @jitendracodehacker for letting us know, it still depends on influxdata/influxdb#18391 . The client example uses [a proxy](https://github.com/influxdata/influxdb-client-js/blob/master/examples/scripts/server.js) to workaround 1.8 CORS issues.

**Comment by jitendracodehacker** [comment]
Thank you .. but still i am facing the issue. here is the output of my node server 
![image](https://user-images.githubusercontent.com/25054529/100429644-9e6ea100-30bb-11eb-9238-56d8206fe3b2.png)

could you check this . 

my setup is :
i have running angular application on my machine and influx db is deployed to AWS EC2 instance.

**Comment by sranka** [comment]
It should be fine if your angular APP is served from the same server where the proxy is running, no CORS is then used. You can also add [cors](https://expressjs.com/en/resources/middleware/cors.html) to the proxy server, so that the proxy can be accessed from any origin.
