### ISSUE TITLE
Roadmap for some early release for testing

### ISSUE THREAD

**Issue by YoleYu** [influxdata/influxdb-client-js#20]
HI, 
I want to know is there any roadmap for js client of V2, I am doing some investigation for a project if we should use v2.

**Comment by bthesorceror** [comment]
Currently we are developing the client as we develop influxdb 2.0 and as such are building the features we use for the frontend ui as they are needed. We expect that the javascript library will be fully stable along with the GA release of influxdb 2.0. If during your testing you find any issues we would love to hear from you.

**Comment by bednar** [comment]
The client is released as a new npm package: `@influxdata/influxdb-client`. If this issue is still relevant for the new client, please feel free to create new issue.
