### ISSUE TITLE
timestamp on Point not written to timestamp in InfluxDB

### ISSUE THREAD

**Issue by ronaldplevier** [influxdata/influxdb-client-js#206]
## Expected Behavior
I would expect that the timestamp value on the Point class is written to the timestamp field in InfluxDB and that the Stop timestamp in Influx is set to the current date. Equal to when writing data to influxDB via the command line.

## Current Behavior
The value is written to the Stop timestamp in InfluxDB.
Timestamp is set to 1970 xxxx

## Steps/Code to Reproduce the Problem

    const data = response.data.map(records => {
      return new Point('X')
        .timestamp(candle[0])

      });

    influxWriteApi.writePoints(data);

## Specifications

- Version: 1.3.0
- Platform: 
     - OSX: 10.15.1
     - Node.js: 10.16.2
     - influx: 2.0

**Comment by sranka** [comment]
@ronaldplevier Can you pls also share the value of candle[0]. The value that is sent to InfluxDB depends on the type of candle[0]. You could also serialize a Point to log what is sent to InfluxDB to know what then sent to InfluxDB:

```
console.log(new Point('X').timestamp(candle[0]).toLineProtocol(influxWriteApi))
```

[Point.ts#L126](https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/Point.ts#L126) is documented to describe possible values that are accepted by [the implementation]([https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/impl/WriteApiImpl.ts#L238), there is also [a test](https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/test/unit/WriteApi.test.ts#L235))

**Comment by ronaldplevier** [comment]
Sranka,

The values in candle[0] are in the unix second timestamp.
time:1582758000
time:1582754400
time:1582750800
time:1582747200
time:1582743600
time:1582740000

But if I understand you correctly then the format provided will determine if it ends up in Start, Stop or timestamp field on the DB side?

Could not make that up from the code.

BTW. I tried the line of code you provided, but it doesn't like the influxWriteApi part as it wants to have a point setting.

**Comment by sranka** [comment]
@ronaldplevier 
- there is only one timestamp when you write data
- the default precision of the write API is *nanoseconds*, https://github.com/influxdata/influxdb-client-js/blob/master/examples/write.js#L11 - do you use `'s'` precision when you create the write API?
- https://github.com/influxdata/influxdb-client-js/blob/master/examples/write.js#L27 is an example that writes protocol line

**Comment by sranka** [comment]
https://github.com/influxdata/influxdb-client-js/blob/master/examples/write.js#L25 also explains what is the timestamp unit when a number is supplied

**Comment by ronaldplevier** [comment]
Sranka,

My apologies.
Finally understand what's happening. Should not have left out some line of codes as it would heave been clear from the start.
I'm writing a Point with a field set and in that case only the Stop timestamp is set and not the timestamp, which makes sense, but not what I was expecting or very clear documented.

So no issue with the client.
