### ISSUE TITLE
Empty numbers should be converted to null instead of 0

### ISSUE THREAD

**Issue by neben** [influxdata/influxdb-client-js#227]
__Expected Behavior:__

If a query returns a field of type `number` that does not have a value, e.g., after pivoting, this empty field should be converted to `null` by the `tableMeta.toObject()` function.

__Current Behavior:__

If a query returns a field of type `number` that does not have a value, e.g., after pivoting, this empty field is converted to the number 0 by the `tableMeta.toObject()` function. This makes it impossible to distinguish between, e.g., a valid sensor reading of 0 or a missing value in the dataset, i.e., `null`.

__Possible Solution:__
Change this [code line](https://github.com/influxdata/influxdb-client-js/blob/4343aae250ba66588c4171bf64ed920e0beba543/packages/core/src/query/FluxTableMetaData.ts#L13) from 
```
double: (x: string): any => +x,
```
to
```
double: (x: string): any => x === '' ? null : +x
```

__Steps/Code to Reproduce the Problem:__
without converting the rows:
```
await queryApi.collectRows(influxQuery, row => row);

[
  [ '', '0', '1234000000', '15.2', '', '' ]
]
```
with converting the rows:
```
await queryApi.collectRows(influxQuery);

[
  {
    result: '_result',
    table: '0',
    time: 1234000000,
    'sensors/test/floorA/sensor1': 15.2,
    'sensors/test/floorA/sensor2': 0,         // <--------- should be null
    'sensors/test/floorB/sensor1': 0          // <--------- should be null
  }
]
```

__Specifications:__

- Version: latest
- Platform: linux

**Comment by sranka** [comment]
Thank you for reporting this issue. Yes, there might better default type serializers. You can already customize it the way you like: 
```
import { typeSerializers } from '@influxdata/influxdb-client'

typeSerializers.double = (val) => val === '' ? null : +val
``
