### ISSUE TITLE
Package not found in npm registry

### ISSUE THREAD

**Issue by MclloydVuong** [influxdata/influxdb-client-js#232]
__Current Behavior:__
Hi, I'm currently experiencing an issue installing this package
when running `npm i @influxdata/influxdb-client` package is not found in npm registry.

__Steps/Code to Reproduce the Problem:__

1. run `npm i @influxdata/influxdb-client` 

__Specifications:__

- Version: latest
- Platform: ubuntu

**Comment by sranka** [comment]
`npm i @influxdata/influxdb-client` works for me. It might be caused by a different networking/proxy/registry configuration of npm client.

**Comment by sranka** [comment]
See also https://www.npmjs.com/package/@influxdata/influxdb-client

**Comment by smalik2043** [comment]
For me it is not working. I am running ubuntu version 18. 

```$ yarn add @influxdata/influxdb-client
yarn add v1.22.4
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@influxdata%2finfluxdb-client: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/home/ubnutu/projects/my-project/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.```

```e$ yarn install
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/@influxdata%2finfluxdb-client: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/home/ubnutu/projects/my-project/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.```

**Comment by sranka** [comment]
FYI: it works for me: `yarn add --verbose @influxdata/influxdb-client`  
```
[1/4] Resolving packages...
verbose 0.161973547 Performing "GET" request to "https://registry.yarnpkg.com/@influxdata%2finfluxdb-client".
verbose 1.957506046 Request "https://registry.yarnpkg.com/@influxdata%2finfluxdb-client" finished with status code 200.
```

**Comment by MclloydVuong** [comment]
This is strange, it was working for me yesterday. and this is an issue since today for both my local machine and ci server.

**Comment by bednar** [comment]
Maybe it is related to 

>Investigating - We are investigating reports of issues when accessing the npmjs.com website. 
Aug 6, 08:29 UTC

https://status.npmjs.org

**Comment by MclloydVuong** [comment]
yes it is! thanks! sorry for taking your time. :pray:
