### ISSUE TITLE
dateTime typeSerializer doesn't handle "dateTime:RFC3339"

### ISSUE THREAD

**Issue by bettse** [influxdata/influxdb-client-js#239]
This list:
https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/query/FluxTableMetaData.ts#L16

[Doesn't ever match](https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/query/FluxTableMetaData.ts#L56) this dataType: `dateTime:RFC3339`

**Comment by sranka** [comment]
Thank you for reporting this, this type appears as a javascript string. I should better add it explicitly.
