### ISSUE TITLE
String serialization failure while escaping characters

### ISSUE THREAD

**Issue by cTn-dev** [influxdata/influxdb-client-js#241]
__Expected Behavior:__
Measurement with provided string is correctly escaped and written to the DB

__Current Behavior:__
Operation results in `Cannot read property 'escapeChar' of undefined` error.

__Steps/Code to Reproduce the Problem:__

1. The "minimal" string i was able to reproduce the issue with `{"prop":"{\"str\":\"test\"}"}`
2. This type of string escaping is the result of double stringification via JSON.stringify() (object containing a valid JSON string is stringified again)
2. Partially-pseudo code to reproduce the issue (i don't really have any TS experience, i have adopted the 1.8 TS example for this, apologies/did what i could here)
```js
import {ClientOptions, InfluxDB, Point} from '@influxdata/influxdb-client'

const username = 'username'
const password = 'password'

const database = 'telegraf'
const retentionPolicy = 'autogen'

const bucket = `${database}/${retentionPolicy}`

const clientOptions: ClientOptions = {
  url: 'http://localhost:8086',
  token: `${username}:${password}`,
}

const influxDB = new InfluxDB(clientOptions)
const writeAPI = influxDB.getWriteApi('', bucket)

const point = new Point('testMeasurement');

// THE IMPORTANT PART
point.stringField('testField', '{"prop":"{\"str\":\"test\"}"}');

writeAPI.writePoint(point)
writeAPI
  .close()
  .then(() => console.log('FINISHED'))
  .catch(error => {
    console.error(error)
  })
```

The very likely cause is an edge case related to #205 on https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/util/escape.ts#L60

__Specifications:__

- Version: InfluxDB 1.8.1 & influxdb-client-js 1.6.0
- Platform: Linux & node.js 12.18.3

**Comment by sranka** [comment]
Thank you for reporting the issue together with the test case. I think that the test case fails on  `'{"prop":"{\\"str\\":\\"test"\\}"}'. This is indeed a client-side defect that could be reproduced without InfluxDB connection with:.

```
const {Point} = require('@influxdata/influxdb-client')

const point = new Point('testMeasurement')

// THE IMPORTANT PART
const field2 = '{"prop":"{\\"str\\":\\"test"\\}"}'
console.log('field2', field2)
point.stringField('f2', field2)
console.log(point.toLineProtocol())
// TypeError: Cannot read property 'escapeChar' of undefined
```

I am on it shortly.

**Comment by cTn-dev** [comment]
Thank you very much!

**Comment by sranka** [comment]
@cTn-dev Please upgrade "@influxdata/influxdb-client" to version "1.7.0-nightly.5" that contains the fix. The next release (1.7.0) is likely to happen next month.

**Comment by cTn-dev** [comment]
@sranka Thank you for a quick fix, will gave that a shot
