### ISSUE TITLE
Buffer fills up while using Node.js/Lambda

### ISSUE THREAD

**Issue by joshk132** [influxdata/influxdb-client-js#261]
__Steps to reproduce:__

1. Setup InfluxDB Cloud free tier
2. Write to DB
3. Check logs

```
'use strict';

const {InfluxDB, Point, HttpError} = require('@influxdata/influxdb-client')

const InfluxURL = 'https://us-west-2-1.aws.cloud2.influxdata.com'
const token = 'mytoken'
const org = 'myorg'
const bucket= 'mybucket'

const writeApi = new InfluxDB({url: InfluxURL, token}).getWriteApi(org, bucket, 'ms')

module.exports.perf = async (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = false;

  let input = JSON.parse(event.Records[0].body);
  console.log(input)

  const point1 = new Point('elapsedTime')
    .tag(input.foo, 'foo')
    .floatField('value', input.bar)
  writeApi.writePoint(point1)
  writeApi
  .close()
  .then((result) => {
    console.log(result)
  })
  .catch(e => {
    console.error(e)
    if (e instanceof HttpError && e.statusCode === 401) {
    
    }
    console.log('\nFinished ERROR')
  })

  return true
};

```

__Expected behavior:__
I expect it to write every data point to the DB for each SQS message - takes one message with one data point per lambda execution. 

__Actual behavior:__
It fills the buffer - which IDK how to clear - and prevents any data from being written to the DB

__Environment info:__
Cloud offering free tier on AWS us-west-2

__Logs:__
`ERROR: Retry buffer closed with 1 items that were not written to InfluxDB!`

__Notes:__
I did manage to write one data point a few days ago and since then it has been not letting me write anything saying the buffer is full

**Comment by sranka** [comment]
@joshk132, 
- the write API is closed from a function that is not creating it, this might cause problems
- the **perf** function is async, therefore you should better **await writeApi.close**, and you can then avoid (promise's) then/catch blocks

Please see also https://community.influxdata.com/t/problem-writing-to-influxdb-cloud-from-aws-lambda/15705 that also contains some tips and advices about InfluxDB JS client in AWS lambda.

**Comment by ZaneL** [comment]
Thank you!

That was the problem -- looks like I just needed to await on writeApi.close()
