### ISSUE TITLE
Authorization token not applied in Safari & Firefox

### ISSUE THREAD

**Issue by MarkLyck** [influxdata/influxdb-client-js#262]
__Expected Behavior:__

influxdb-client-js should work in node and major browser environments.

__Current Behavior:__

influxdb-client-js works fine in Google Chrome, but the network requests it makes fails in both latest version of Safari and latest version of Mozilla Firefox. The network requests are identical except for a missing Authorization token in both Safari and Firefox.

The OPTIONS request goes through with a 200 OK, but the POST request fails:

<img width="1130" alt="Screen Shot 2020-09-23 at 22 58 11" src="https://user-images.githubusercontent.com/6841110/94099447-9317a480-fdf0-11ea-82d8-0bb9b8cb7709.png">

The exact same request works fine in Google Chrome where the Authorization header & is applied:

<img width="1114" alt="Screen Shot 2020-09-23 at 23 01 48" src="https://user-images.githubusercontent.com/6841110/94099522-c3f7d980-fdf0-11ea-8516-41e0c1aa710a.png">

the response from Firefox is simply Unauthorized (unsurprisingly since it was sent without an auth token)
```
code | "unauthorized"
message | "unauthorized access"
```

Request headers sent in Firefox:

```
Accept | text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding | gzip, deflate, br
Accept-Language | en-US,en;q=0.5
Connection | keep-alive
Host | eu-central-1-1.aws.cloud2.influxdata.com
TE | Trailers
Upgrade-Insecure-Requests | 1
User-Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0
```

Notice the Authorization header is not there.

For comparison these are the request headers sent from Chrome:

```
:authority: eu-central-1-1.aws.cloud2.influxdata.com
:method: POST
:path: /api/v2/query?org=john%40sensefence.dk
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,da;q=0.8
authorization: Token HIDDEN==
content-length: 611
content-type: application/json; encoding=utf-8
origin: http://localhost:3000
referer: http://localhost:3000/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
```

I am running the exact same front-end application locally on localhost:3000, and accessing it on: Chrome, Safari and Firefox. There are 0 code differences between them.

I have console.logged both my token (from environmennt variables and the influxDB client to exist). I also see the token applied correctly to the influxDB client:

Here is the console.log of the influxDB client: (in Firefox)

```
{
  "_options": {
    "url": "https://eu-central-1-1.aws.cloud2.influxdata.com",
    "token": "HIDDEN=="
  },
  "transport": {
    "connectionOptions": {
      "url": "https://eu-central-1-1.aws.cloud2.influxdata.com",
      "token": "HIDDEN=="
    },
    "chunkCombiner": {},
    "defaultHeaders": {
      "content-type": "application/json; charset=utf-8",
      "User-Agent": "influxdb-client-js/1.6.0",
      "Authorization": "Token HIDDEN=="
    }
  }
}
```

I have replaced the real token with `HIDDEN==` as it is a private token. But I have verified the actual token is correct, and it's the same one that is working fine in Chrome.

Lastly it is worth noting, all network requests to other API's than influxDB all work fine in all 3 browsers and the Authorization tokens are applied correctly from another API client and from my standard `fetch` requests. This problem only happens with `influxdb-client-js`

__Steps/Code to Reproduce the Problem:__

1. make a simple query and test it to work in Chrome
1. run the same app in Safari & Firefox and it fails.

__Specifications:__

- Version: "@influxdata/influxdb-client": "^1.6.0",
- Platform: MacOS Catalina, Safari (latest), Firefox (Latest)

**Comment by sranka** [comment]
Thank you for reporting this issue and the detailed logs, it will help with a deeper investigation.

**Comment by sranka** [comment]
I am on it now, it is also reproducible with FF80.0.1 on Linux.

**Comment by sranka** [comment]
InfluxDB client modifies "User-Agent' header (in order to collect usage statistics), but this header is not authorized in a pre-flight request. It seems to be a cloud-specific issue, the InfluxDB server itself already authorizes this header for 6 months ( https://github.com/influxdata/influxdb/blob/550966dbe28493be530e1587aa76994a2eaa2810/kit/transport/http/middleware.go#L30 )

The workaround is to remove this header after creating an InfluxDB instance.
```
      const influxDB = new InfluxDB({url, token})
      delete influxDB.transport.defaultHeaders['User-Agent']
```

**Comment by sranka** [comment]
@russorat can you please find somebody who can fix this in the cloud, or transfer this issue therein?

subject: InfluxDB javascript browser clients are not authorized to access cloud instance (Safari, FF + different origin)
__Current Behavior__:
A CORS (HTTP OPTIONS) preflight response to 'https://eu-central-1-1.aws.cloud2.influxdata.com' does not include 'User-Agent' header, it is:
```
access-control-allow-methods: POST, GET, OPTIONS, PUT, DELETE
access-control-allow-headers: Accept, Content-Type, Content-Length, Accept-Encoding, Authorization
```

__Expected Behavior__
Cloud deployment ensures that responses to v2 API CORS preflight request (HTTP OPTIONS) include `PATCH` in `Access-Control-Allow-Methods` header and `User-Agent` in `Access-Control-Allow-Headers` header. For example:
```
Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE, PATCH
Access-Control-Allow-Headers: Accept, Content-Type, Content-Length, Accept-Encoding, Authorization, User-Agent
```

**Comment by russorat** [comment]
Thanks! i am following up on this internally.

**Comment by sranka** [comment]
@russorat I tried this again today, there is no change in the cloud regarding CORS support for Firefox and Safari. 

It still works in Chrome and Opera. It works only because a custom setting of User-Agent header (being influxdb-client-js/1.x.x)  is always silently ignored (independently on CORS) by the browser, Chrome and Opera do not seem to allow to change User-Agent request header from the code at all. I guess removing the custom User-Agent header is then a good solution when the client is used in the browser.
