### ISSUE TITLE
`getReady` in` ReadyAPI` it returns a promise that resolves  as a `JSON text`

### ISSUE THREAD

**Issue by mprevide** [influxdata/influxdb-client-js#277]
__Expected Behavior:__

When I call `getReady` in` ReadyAPI` it returns a promise that resolves  as an `object`

__Current Behavior:__

When I call `getReady` in` ReadyAPI` it returns a promise that resolves  as a ` JSON text`

**Comment by sranka** [comment]
Thank you for reporting an issue. InfluxDB server wrongly returns "Content-Type": "text:plain" whereas the API is described to return "application/json". A workaround is straightforward, in place of `readyAPI.getReady()`, use
```
readyAPI.getReady().then(x => (typeof x === 'string' ? JSON.parse(x) : x))
```

**Comment by sranka** [comment]
The server has been fixed, the workaround won't be required since the next server release.
