### ISSUE TITLE
Doesn't call the function set at `writeOptions.writeSuccess `

### ISSUE THREAD

**Issue by mprevide** [influxdata/influxdb-client-js#279]
__Expected Behavior:__

Should call the function set at `writeOptions.writeSuccess` when data has written.

__Current Behavior:__

Doesn't call the function set at `writeOptions.writeSuccess ` but data has written. 

__Steps/Code to Reproduce the Problem:__

```
....

writeOptions.writeFailed = (error, lines, attempts) => {
      logger.error(`writeFailed: lines: ${lines.toString()} attempts:${attempts}`, error);
    };

writeOptions.writeSuccess = (lines) => {
      console.log(`writeSuccess: lines: ${lines.toString()}`);
    };

influxDB.getWriteApi(
            org,
            bucket,
            precision,
            writeOptions,
          ),
```

**NOTE: When I used `writeOptions.writeFailed` the defined function is called when has some error.** 

__Specifications:__

- Version:
- Platform:

**Comment by sranka** [comment]
Thank you for reporting an issue, the `writeSuccess` function will be available in the next release (1.9.0). Use the latest nightly build, **1.9.0-nightly.982**, to meet the expectations.
