### ISSUE TITLE
Error objects  

### ISSUE THREAD

**Issue by mprevide** [influxdata/influxdb-client-js#284]
__Expected Behavior:__

```js
          error(error) {
            const { message, statusMessage, statusCode } = error;
```

I think the pattern has a name and a message inside the error.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Error

__Current Behavior:__

```js
          error(error) {
            const { message } = error.body ? JSON.parse(error.body) : {};
            const { statusMessage, statusCode } = error;
```

__Specifications:__

- Version: 1.8

**Comment by sranka** [comment]
An error must have name and message properties. I will add a test to check that all the client's custom errors do. Can you please be more specific about the current behavior, I don't see any code pointing to this client.

**Comment by sranka** [comment]
The tests are fine, I also created #285 that probably better describes your original intentions.
