### ISSUE TITLE
dashboards API createLabel naming and errors are misleading

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/influxdb-client-js#30]
createLabel does not create a label, it adds a label that already exists to a dashboard. 
error message `Failed to create label` is also misleading in the same vein. 
Also, the error message is generated if dashboard is returned with no label property. If a dashboard already had another label, but failed to add new label, this error would not throw?

**Comment by OfTheDelmer** [comment]
Seems related to https://github.com/influxdata/influxdb2-js/issues/22

**Comment by bednar** [comment]
The client is released as a new npm package: `@influxdata/influxdb-client`. If this issue is still relevant for the new client, please feel free to create new issue.
