### ISSUE TITLE
Support await/async pattern

### ISSUE THREAD

**Issue by dtosato** [influxdata/influxdb-client-js#300]

**Comment by sranka** [comment]
Can you pls be more specific? If you need to await for data write, you can `await writeApi.flush()` ... and possibly adjust internal write buffer size to ensure that your data are not flushed automatically. See https://github.com/influxdata/influxdb-client-js/blob/master/examples/writeAdvanced.js .

**Comment by sranka** [comment]
It is an intention to write without await, so that communication with InfluxDB is optimized in batches and retried automatically.

**Comment by dtosato** [comment]
@sranka, thanks, now it is clear to me.
