### ISSUE TITLE
Getting token using username & password from the client (2.X)

### ISSUE THREAD

**Issue by shashankvivek** [influxdata/influxdb-client-js#301]
In InfluxDB1.X , I can see that we can create a client using:

```

    const clientOptions: ClientOptions = {
      url: 'http://localhost:8099',
      token: `username:password`
    }

    const influxDB = new InfluxDB(clientOptions)    

    const queryApi = influxDB.getQueryApi('org_name')
        queryApi.queryRows(this.fluxQuery, {
          next(row, tableMeta) {
            const o = tableMeta.toObject(row)
            if (o.element){
              console.log(o);              
            } else {
              // default output
              console.log(JSON.stringify(o, null, 2))
            }
          },
          error(error) {
            console.log('QUERY FAILED', error)
          },
          complete() {
            console.log('QUERY FINISHED')
          },
        })
```

For `InfluxDB2.X` , the token has to be provided as shown in [example section](https://github.com/influxdata/influxdb-client-js/blob/master/examples/index.html) using `env.js`.  But then how to get this token on Client side ? I do not see any documentation for such token provider endpoint even in API documentation as well

**Comment by sranka** [comment]
You can create a token using InfluxDB v2 administration UI in its `Data` / `Tokens` section. The token authentication is the preferred choice for any programmatic access to InfluxDB. Do you need a way to automate the retrieval or creation of the token?

**Comment by sranka** [comment]
#302 introduces a few changes and a `tokens.js` example that shows how to use username+password authentication in order to automate the management of authorization tokens.

**Comment by shashankvivek** [comment]
> #302 introduces a few changes and a `tokens.js` example that shows how to use username+password authentication in order to automate the management of authorization tokens.

@sranka : Thank you so much, I'll give it a try now

**Comment by sranka** [comment]
@shashankvivek `tokens.js` demo will work with a snapshot release once #302 is merged to master or in the next release (~1 month)
