### ISSUE TITLE
Query API - Gzip enabled - Only returns table 0

### ISSUE THREAD

**Issue by mmuller99** [influxdata/influxdb-client-js#303]
__Expected Behavior:__

Should return all tables

__Current Behavior:__

Only returns table 0

__Possible Solution:__

__Steps/Code to Reproduce the Problem:__

1. Write to bucket
2. Write query, with gzip enabled that returns multiple tables
3. Only table 0 is returned

__Specifications:__

- Version: 2.0.4
- Platform: Linux

**Comment by sranka** [comment]
Thank your for reporting an issue. I tried the following steps:

1. run a fresh new influxdb 2.04 
    `docker run -d --name influxdb_v2.04 -p 8086:8086 quay.io/influxdb/influxdb:v2.0.4`
1. `cd examples`
1. `yarn` to install dependencies
1. `./onboarding.js`
1. `./write.js` to write a sample data to a first table
1. `./writeAdvanced.js` to write more tables and data
1. modified `query.ts` example
    - request gzip compression in the response, line 9:
      `const queryApi = new InfluxDB({url, token}).getQueryApi(org).with({gzip: true})`
    - query all data to have a bigger result that must be gzipped, line 11:
      'from(bucket:"my-bucket") |> range(start: 0)'
    - print table, line 21:
      `` `${o.table}: ${o._time} ${o._measurement} in '${o.location}' (${o.example}): ${o._field}=${o._value}` ``
1. `./query.ts` prints data from 2 tables.

I can also observe the same results without js client:
`curl -X POST -H 'Authorization: Token my-token' -H 'Content-Type: application/vnd.flux' -H 'Accept-encoding: gzip' -d 'from(bucket:"my-bucket") |> range(start: 0)' http://localhost:8086/api/v2/query?org=my-org --compressed > out.txt` .
   
Can you please try the `curl` example to prove that this client is doing wrong, or provide better instructions to reproduce your issue?

**Comment by sranka** [comment]
@mmuller99 I'll be ready to reopen this once instructions are provided

**Comment by andreivreja** [comment]
Got a similar issue where the response is being truncated at some point (randomly). Can definitely confirm it's at code level, examining the response itself shows the full data set, but the library fails to create the full object (using `collectRows`).

Response size is around 40KB (gzipped).

**Comment by sranka** [comment]
Thank you @andreivreja for letting us know, I'll try a play around a bit more to find out more.

**Comment by sranka** [comment]
The following scenario can reproduce the issue

1. run a fresh new influxdb 2.04 
    `docker run -d --name influxdb_v2.04 -p 8086:8086 quay.io/influxdb/influxdb:v2.0.4`
1. `cd examples`
1. `yarn` to install dependencies
1. `./onboarding.js`
1. `./write.js` to write a sample data to a first table
1. `./writeAdvanced.js` to write more tables and data, run it 20-times
1. modified `query.ts` example
    - request gzip compression in the response, line 9:
      `const queryApi = new InfluxDB({url, token}).getQueryApi(org).with({gzip: true})`
    - query all data to have a bigger result that must be gzipped, line 11:
      `'from(bucket:"my-bucket") |> range(start: 0)'`
    - collect only count of rows
1. `./query.ts` 
    - count 109392 with gzip compression, and 112651 without it

**Comment by sranka** [comment]
I found the root cause, it lies in the usage of piped node streams, the request stream is 'closed' and the last gzip chunk is then left unprocessed  ... and it behaves differently between node versions. I am preparing a fix.

**Comment by mmuller99** [comment]
Thanks @andreivreja @sranka

**Comment by sranka** [comment]
@mmuller99 @andreivreja the fix is now included in the nightly builds, since version "1.23.0-nightly.1720", thank you for your patience
