### ISSUE TITLE
`Self is not defined` when using influxb-client-giraffe `queryToTable` server side.

### ISSUE THREAD

**Issue by Khaaz** [influxdata/influxdb-client-js#307]
With influxdb-client-giraffe, it seems impossible for me to use the package server side because it directly relies on GIraffe. The package that errors at import is giraffe.

Unless I'm missing something I wanted to know if that's expected or not. (Maybe my interpretation is incorrect or I am doing something wrong which is probably the case).

However, if that's expected, I think it's a limitation because we just can't get the influx query to be ran server side which would be in my use case necessary.

__Expected Behavior:__
 
 Run `influxdb-client-giraffe` server side without issue to get parsed data to send to the frond-end to then display with giraffe.

__Current Behavior:__

It error when importing `giraffe` with: `self is not defined` .
I'm guessing it's because `giraffe` is not supposed to be ran server side but I don't know. 

__Possible Solution:__

The package shouldn't rely directly on `giraffe` but rather create a format that can easily parsed by giraffe later without making us use Giraffe directly?

Error:
```
ReferenceError: self is not defined
    at Object.<anonymous> (/mnt/d/Projects/<user>/dashboard/node_modules/@influxdata/giraffe/dist/index.js:2:307)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.@influxdata/giraffe (/mnt/d/Projects/<user>/dashboard/.next/server/pages/api/graph.js:146:18)
    at __webpack_require__ (/mnt/d/Projects/<user>/dashboard/.next/server/pages/api/graph.js:23:31)
    at Module../src/pages/api/graph.js (/mnt/d/Projects/<user>/dashboard/.next/server/pages/api/graph.js:105:77)
```
__Specifications:__

- Version: influxb-client-giraffe 1.10.0, giraffe 2.0.1
- Platform: windows 10

**Comment by sranka** [comment]
Thank you for reporting an issue. 

The stack trace of your next.js application shows that `@influxdata/giraffe` fails to load on the server-side, there is no error in `influxb-client-giraffe`. Please continue with a new issue posted to https://github.com/influxdata/giraffe, I can't transfer it therein.

**Comment by Khaaz** [comment]
Thanks, I'll open an issue directly in the giraffe repository. Since I was not sure I might have done something wrong when using `influxdb-client-giraffe` directly, I thought it could be a good idea opening an issue here first.
I will continue in the aforementioned repository, thank you.

**Comment by sranka** [comment]
Both `influxb-client-giraffe` and `influxdb-client-js` work fine in node, deno or browser. For example, the [queryTable.test.ts](https://github.com/influxdata/influxdb-client-js/blob/master/packages/giraffe/test/unit/queryTable.test.ts) is executed in node. It does not however depend on giraffe, which would likely cause the same issue that you describe.

`influxb-client-giraffe` optimizes retrieval of stream results to a giraffe table. You can also get the whole (possibly big) query response as a string using [QueryApi.queryRaw](https://influxdata.github.io/influxdb-client-js/influxdb-client.queryapi.queryraw.html) and later use giraffe's `fromFlux(queryResultString)` to create a giraffe table.

Another alternative to consider would be to fetch the data only from the browser, either directly or via a server-side proxy as the examples/server.js does.

**Comment by Khaaz** [comment]
Thanks for the clarification and the quick answer. That makes much more sense now.
Sorry for the misunderstanding 👍🏻.
