### ISSUE TITLE
Ability to change log implementation.

### ISSUE THREAD

**Issue by mrxdst** [influxdata/influxdb-client-js#308]
__Proposal:__
Simplest solution: Export the `setLogger` function from `impl/Logger.ts`

__Current behavior:__
The library prints unwanted console messages.

__Desired behavior:__
To be able to redirect log messages to somewhere else.

__Alternatives considered:__
Don't print to the console at all. Make the InfluxDB class an EventEmitter and emit events instead.

__Use case:__
An application uses its own logging implementation. Being able to redirect the log output to it would be useful.

**Comment by sranka** [comment]
Thank you for reporting an issue, the solution is on the way.

**Comment by sranka** [comment]
@mrxdst feel free to use version `1.11.0-nightly.1181` until 1.12 release.
