### ISSUE TITLE
[HttpError]: compilation failed: error at @1:386-1:388: pipe destination must be a function call

### ISSUE THREAD

**Issue by kazomotos** [influxdata/influxdb-client-js#314]
__Expected Behavior:__

Query should return one table with filtered results as it does in data explorer

__Current Behavior:__
Turns out that the map function produces this error while checking if conditions are fulfilled. After removing the map function query returns results. Query results in **[HttpError]: compilation failed: error at @1:386-1:388: pipe destination must be a function call but works in data explorer as expected.**

__Steps/Code to Reproduce the Problem:__

queryApi.collectRows("
import "math"            
from(bucket: "metricx")                
|> range(start: 2020-02-01, stop: 2020-04-01)                
|> filter(fn: (r) => r._measurement == "5ea17827e0ed860742b6ffa0")                
|> filter(fn: (r) => r._field == "value")                
|> filter(fn: (r) => r.id == "5d35f5725d015d3b082f9dea" or r.id == "5d35f5725d015d3b082f9de8" )                        
|> map(fn: (r) => ({            
    r with                
    _value:                      
        if  r._value <= 120 and  r.id == "5d35f5725d015d3b082f9dea" then r._value 
        else if  r._value <= 140 and  r.id == "5d35f5725d015d3b082f9de8" then r._value 
        else -3131313131.3113            
    })        
    )         
|> filter(fn: (r) => r._value != -3131313131.3113)                         
|> aggregateWindow(column: "_value", every: 15m, fn: mean, createEmpty: true)                                
|> pivot(rowKey:["_time"], columnKey: ["id"], valueColumn: "_value")"
)

__Specifications:__

- Version: 1.10
- Platform: Docker quay.io/influxdb/influxdb:2.0.0-rc

**Comment by sranka** [comment]
Thank you for using the client and reporting an issue. I tried a modified `query.ts` example:

```js
const fluxQuery = `
import "math"
from(bucket: "iot_center")
|> range(start: 2020-02-01, stop: 2020-04-01)
|> filter(fn: (r) => r._measurement == "5ea17827e0ed860742b6ffa0")
|> filter(fn: (r) => r._field == "value")
|> filter(fn: (r) => r.id == "5d35f5725d015d3b082f9dea" or r.id == "5d35f5725d015d3b082f9de8" )
|> map(fn: (r) => ({
r with
_value:
if r._value <= 120 and r.id == "5d35f5725d015d3b082f9dea" then r._value
else if r._value <= 140 and r.id == "5d35f5725d015d3b082f9de8" then r._value
else -3131313131.3113
})
)
|> filter(fn: (r) => r._value != -3131313131.3113)
|> aggregateWindow(column: "_value", every: 15m, fn: mean, createEmpty: true)
|> pivot(rowKey:["_time"], columnKey: ["id"], valueColumn: "_value")
`
queryApi.collectRows(fluxQuery)
```

The js client posts the flux script to the server without modifications, so it seems to me that it is likely an issue in a flux script used in your code. Can you please double-check it or send a JS example that I could directly use to reproduce the issue? I was using influxdb 2.04.

**Comment by kazomotos** [comment]
Thank you for quickly responding. I`ve tried the query above again in both data explorer and my application. Data Explorer returns results: 
![image](https://user-images.githubusercontent.com/54186205/108690313-8233a200-74fa-11eb-9977-233b71c3faa0.png)
In my application, there are no further modifications to the flux script. I am a rookie in writing bug reports... how can I provide you a working JS example? I've updated to quay.io/influxdb/influxdb:v2.0.4 but still get the same error message.

import "math"            
from(bucket: "metric")               
|> range(start: 2020-02-01, stop: 2020-04-01)                
|> filter(fn: (r) => r._measurement == "5ea17827e0ed860742b6ffa0")                
|> filter(fn: (r) => r._field == "value")               
|> filter(fn: (r) => r.id == "5d35f5725d015d3b082f9dea" or r.id == "5d35f5725d015d3b082f9de8" )                        
|> map(fn: (r) => ({           
 r with                
_value:                      
   if  r._value <= 120 and  r.id == "5d35f5725d015d3b082f9dea" then r._value 
   else if  r._value <= 140 and  r.id == "5d35f5725d015d3b082f9de8" then r._value 
   else -3131313131.3113           
 })        )         
|> filter(fn: (r) => r._value != -3131313131.3113)                         
|> aggregateWindow(column: "_value", every: 15m, fn: mean, createEmpty: true)
|> pivot( rowKey:["_time"],  columnKey: ["id"], valueColumn: "_value" )

[HttpError]: compilation failed: error at @1:386-1:388: pipe destination must be a function call
    at IncomingMessage.<anonymous> (/home/marc/software/metricx-next-gen/backend/node_modules/@influxdata/influxdb-client/dist/index.js:16:9350)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:486:12)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  statusCode: 400,
  statusMessage: 'Bad Request',
  body: '{"code":"invalid","message":"compilation failed: error at @1:386-1:388: pipe destination must be a function call"}',
  contentType: 'application/json; charset=utf-8',
  json: {
    code: 'invalid',
    message: 'compilation failed: error at @1:386-1:388: pipe destination must be a function call'
  },
  code: 'invalid',
  _retryAfter: 0
}

**Comment by sranka** [comment]
> In my application, there are no further modifications to the flux script. I am a rookie in writing bug reports... how can I provide you a working JS example?

The piece of code that you originally provided in the issue description has quoting errors, so I provided an example of my code and your second flux script is now good enough. Unfortunately, I still can't reproduce it. The influxdb error points to the end of the `if line` ... maybe that some whitespaces might change the game a bit.

A few wild thoughts:
- Are you using the same INFLUX_URL in the browser and in the node example? 
- Can you execute the same query from the browser ... run `yarn browser` and paste  your query therein?

**Comment by kazomotos** [comment]
You are right I simply put it in quotes for this post...

- yes, I am using same URL
- I tried to compact it, does not work either. Map is unfortunately not useless. I`ve already tried to use filter but it turns out that a query like: 

import "math"            
from(bucket: "metricx")                
|> range(start: 2020-02-01, stop: 2020-04-01)               
|> filter(fn: (r) => r._measurement == "5ea17827e0ed860742b6ffa0")                
|> filter(fn: (r) => r._field == "value")                
|> filter(fn: (r) => (r.id == "5d35f5725d015d3b082f9dea" and r._value <= 25.0) or (r.id == "5d35f5725d015d3b082f9de8" and r._value <= 35.0) )
does not filter values above 25 for tag "5d35f5725d015d3b082f9dea". 

- The copied from a console.log directly before the function call collectRows()

**Comment by sranka** [comment]
I can't reproduce it. A networking dump might help:

- `cd examples` in this repository
- yarn add http-proxy
- copy the code below to a new file `issue314.ts`
- run the code with `yarn ts-node issue314.ts` and paste the output as a comment herein

```
#!./node_modules/.bin/ts-node
import {InfluxDB, FluxTableMetaData} from '@influxdata/influxdb-client'
import {HealthAPI} from '@influxdata/influxdb-client-apis'
import {url, token, org} from './env'

console.log(`Target url: ` + url)
const {createServer} = require('http')
const proxy = require('http-proxy').createProxyServer()
const server = createServer(function(req, res) {
  proxy.web(req, res, {target: url})
})
server.on('connection', socket => socket.pipe(process.stdout))

const host = 'localhost'
const port = 3001
server.listen({host, port}, async () => {
  console.log(`listening on http://${host}:${port} and forwarding to ${url}`)
  const influxDB = new InfluxDB({
    url: `http://${host}:${port}`,
    token,
  })
  const health = await new HealthAPI(influxDB).getHealth()
  console.log(JSON.stringify(health))
  console.log()

  const queryApi = influxDB.getQueryApi(org)
  const fluxQuery = `
  import "math"
  from(bucket: "metricx")
  |> range(start: 2020-02-01, stop: 2020-04-01)
  |> filter(fn: (r) => r._measurement == "5ea17827e0ed860742b6ffa0")
  |> filter(fn: (r) => r._field == "value")
  |> filter(fn: (r) => r.id == "5d35f5725d015d3b082f9dea" or r.id == "5d35f5725d015d3b082f9de8" )
  |> map(fn: (r) => ({
  r with
  _value:
  if r._value <= 120 and r.id == "5d35f5725d015d3b082f9dea" then r._value
  else if r._value <= 140 and r.id == "5d35f5725d015d3b082f9de8" then r._value
  else -3131313131.3113
  }) )
  |> filter(fn: (r) => r._value != -3131313131.3113)
  |> aggregateWindow(column: "_value", every: 15m, fn: mean, createEmpty: true)
  |> pivot( rowKey:["_time"], columnKey: ["id"], valueColumn: "_value" )
  `

  queryApi.queryRows(fluxQuery, {
    next(row: string[], tableMeta: FluxTableMetaData) {
      const o = tableMeta.toObject(row)
      console.log(JSON.stringify(o, null, 2))
    },
    error(error: Error) {
      console.log('\nFinished ERROR')
      console.error(error)
    },
    complete() {
      console.log('\nFinished SUCCESS')
    },
  })
})
```

**Comment by kazomotos** [comment]
Your script works as expected but mine still don't. Guess this is a problem on my side... 
Do you know if there is any chance to set values to null in a map function?

**Comment by kazomotos** [comment]
Thank you for your time!

**Comment by sranka** [comment]
> Do you know if there is any chance to set values to null in a map function?

Feel free to ask at https://community.influxdata.com/c/fluxlang/10 or https://influxcommunity.slack.com/archives/CH8RGRW4T .
