### ISSUE TITLE
How to set up policy

### ISSUE THREAD

**Issue by Ls-piao** [influxdata/influxdb-client-js#315]
__Proposal:__
I suggest adding a method of writing and saving policy to writeapi

__Current behavior:__
Now I can write data but I don't have a configuration policy

__Desired behavior:__
I suggest adding a method of writing and saving policy to writeapi

__Alternatives considered:__
nothing

__Use case:__
Because the current amount of data is too large, some data is not needed

**Comment by sranka** [comment]
The whole [InfluxDB public API](https://docs.influxdata.com/influxdb/v2.0/api/) is included in the client. Management of buckets with their retention policies including.
