### ISSUE TITLE
Negative float

### ISSUE THREAD

**Issue by bettse** [influxdata/influxdb-client-js#317]
Does float not support negative? https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/query/flux.ts#L125

**Comment by sranka** [comment]
Thank you for reporting a defect. Yes, the `flux` template string as well as [fluxFloat](https://github.com/influxdata/influxdb-client-js/blob/v1.11.0/packages/core/src/query/flux.ts#L191) do not support negative numbers, I am about to fix it. As a workaround, you can wrap a number value into [fluxExpression](https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/query/flux.ts#L191).

**Comment by sranka** [comment]
The fix will be also available also in a [nightly build](https://www.npmjs.com/package/@influxdata/influxdb-client?activeTab=versions) once #318 is approved and merged.
