### ISSUE TITLE
Set proxy Url in InfluxDB constructor

### ISSUE THREAD

**Issue by martibenn** [influxdata/influxdb-client-js#319]
__Proposal:__
Hello, I'm trying to us influxdb-client-js over a corporate proxy but I don't know how to pass this information to the `new InfluxDB(...)` part of the code.
I'm not using the browser version, only the classic access

__Current behavior:__
InfluxDB constructor doesn't seems to accept a proxy url parameter.
I've seen that the [python lib](https://influxdb-python.readthedocs.io/en/latest/api-documentation.html#influxdbclient) accept this parameter by I can't find the same in the js lib

__Desired behavior:__
Can pass a proxy url parameter

__Alternatives considered:__
Point me to some documentation please :)

__Use case:__
I work behind a corporate proxy and I need to pass by this proxy to access the remote influxdb server

**Comment by sranka** [comment]
Thank you for using the client and reporting the defect, I am on it shortly.

**Comment by sranka** [comment]
@martibenn You can create a [proxy-agent](https://www.npmjs.com/package/proxy-agent) and pass it as an `agent` [transport option](https://influxdata.github.io/influxdb-client-js/influxdb-client.connectionoptions.html) to `InfluxDB` constructor. The code can then look like:

```js
const proxyURL = process.env.HTTP_PROXY | 'http://your-proxy:8080'
const proxyAgent = require('proxy-agent')(proxyUrl);
...
new InfluxDB({url, transportOptions: {agent: proxyAgent}) 
```

**Comment by martibenn** [comment]
Working well !
I didn't know what could be set in the [transportOptions](https://influxdata.github.io/influxdb-client-js/influxdb-client.clientoptions.transport.html) param
Thank you very much for the help !
