### ISSUE TITLE
Can't import the named export 'Buffer' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by aguynamedben** [influxdata/influxdb-client-js#321]
I have a codebase that is generally modern ES6 + Babel + Webpack + Electron. When I added this gem, everything worked in development, but when I went to package the app for production, the build failed due to this error:

![image](https://user-images.githubusercontent.com/107841/113471866-18b98400-9414-11eb-9d33-7b07d9189d72.png)

Any ideas? From this package's dist/package.json, it seems there are some rules specifying if I use `import` to use the non-working dist/index.mjs file. The workaround to point at dist/index.js works fine:

```js
import { InfluxDB, WriteApi } from '@influxdata/influxdb-client/dist/index.js';
```

I read something about Node 14 supporting .mjs better, but I upgraded to Node 14 using nvm and I still get the error. Any tips? I've been doing JavaScript for several years now, this seems like a tooling nuance that's not playing well with my codebase or my level of package.json expertise.

Thanks!

Node v14.16.0
influxdb-client-js 1.12.0
@babel/* 7.12.*
webpack 4.44.2

**Comment by sranka** [comment]
This is most likely an issue with webpack configuration. Switching from `@influxdata/influxdb-client` to `@influxdata/influxdb-client-browser` should resolve your issue. 

Explanation: `@influxdata/influxdb-client` package.json contains
```
  "main": "dist/index.js",
  "module": "dist/index.mjs",
  "module:browser": "dist/index.browser.mjs",
  "browser": "dist/index.browser.js",
```
where 'main' and 'module' target node.js environment; AFAIK webpack preffers the `browser` distribution for web development, it depends on its configuration.

`@influxdata/influxdb-client-browser` contains
```
  "main": "dist/index.browser.js",
  "module": "dist/index.browser.mjs",
  "module:browser": "dist/index.browser.mjs",
  "browser": "dist/index.browser.js",
```
All 'main', 'module` target browser distribution of the client.

The only big difference between `@influxdata/influxdb-client-browser` and `@influxdata/influxdb-client` is a transport layer (browser fetch vs node http/https), the client API is the same.

**Comment by namgk** [comment]
do you know how to configure webpack for node js application instead of the browser?

Thanks

**Comment by alex-mironov** [comment]
Faced the same issue with serverless. Fixed by adding a webpack.config:
```
'use strict';

const slsw = require('serverless-webpack');

module.exports = {
    entry: slsw.lib.entries,
    mode: 'development',
    externals: [
        'aws-sdk'
    ],
    target: 'node',
    module: {
        rules: [
            {
                test: /\.mjs$/,
                include: /node_modules/,
                type: 'javascript/auto', // Necessary for properly resolving mjs
            },
        ],
    }
};


```
