### ISSUE TITLE
Document how to write large numbers.

### ISSUE THREAD

**Issue by MicahZoltu** [influxdata/influxdb-client-js#323]
__Proposal:__
Write some documentation somewhere that explains how to send 64 bit numbers (like nanosecond timestamps) via this library.

__Current behavior:__
I want to write a nanoseconds timestamp, but JavaScript `number` loses integer precision beyond 2^53.

__Desired behavior:__
Documentation that tells me how I can write a point with a nanosecond timestamp that doesn't get wiped out by JavaScript.

__Alternatives considered:__
Maybe I can pass a base 10 string?  Maybe a base 16 string starting with `0x`?  Maybe a `bigint`?  Maybe none of these and I just cannot write 64-bit numbers?

__Use case:__
I have incoming data that is `bigint` and fits in 64-bits and I want to write it to InfluxDB via this library.

**Comment by sranka** [comment]
The current documentation is in https://influxdata.github.io/influxdb-client-js/influxdb-client.point.timestamp.html
```
Point.timestamp() method
Sets point time. A string or number value can be used to carry an int64 value of a precision that depends on WriteApi, nanoseconds by default. An undefined value generates a local timestamp using the client’s clock. An empty string can be used to let the server assign the timestamp.
```

The answer for your case is a string value, it is a base-10 string.

**Comment by MicahZoltu** [comment]
Is it possible for random people like me to submit a PR to those docs?  I would like to update it to be more clear on exactly what subset of "string" is allowed.

**Comment by sranka** [comment]
Sure, [contributions](See https://github.com/influxdata/influxdb-client-js#contributing) are welcome ... the documentation is generated from the code, in this case:

https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/Point.ts#L125-L135 . 

The current implementation can also handle a bigint value without complaints. A Bigint in a typescript signature might cause problems to runtimes that don't have a bigint yet. Should be better `undefined`. Feel free to include it as well (with tests).
