### ISSUE TITLE
How to write points with Gzip compression ? 

### ISSUE THREAD

**Issue by forzapa** [influxdata/influxdb-client-js#325]
I noticed in the InfluxDB documentation that we could speed up writes by using gzip compression. 
https://docs.influxdata.com/influxdb/v2.0/write-data/best-practices/optimize-writes/?t=Client+libraries

Is it something that has not been implemented, or I am just blind and did not find it in the documentation? 
Thank you very much

**Comment by sranka** [comment]
Thank you @forzapa for using the js client and creating an issue. The JS client currently does not gzip writes. I am adding this for the next release. The client implementation will then do gzip OOTB based on a threshold (>2000 bytes -> gzip) + a developer will have an option to change the threshold.
