### ISSUE TITLE
How to get all measurement from one bucket ?

### ISSUE THREAD

**Issue by weishijun14** [influxdata/influxdb-client-js#330]
I cant find any api about get all measurement or get one measurement from bucket?
But I can find in here: [https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb-schema/measurements/](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb-schema/measurements/)
Please give me some path?
Thanks !

**Comment by sranka** [comment]
The query is a FLUX script that returns tables. The query can be
```
import "influxdata/influxdb/schema"

schema.measurements(bucket: "example-bucket")
```

**Comment by wesley-jun** [comment]
Resolved:
```
const queryApi = this.influxDB.getQueryApi(process.env.INFLUXDB_ORG);
const fluxQuery = flux`import "influxdata/influxdb/schema" schema.measurements(bucket: "xxx")`;
```
