### ISSUE TITLE
Point.toLineProtocol() should write in ns precision by default.

### ISSUE THREAD

**Issue by empz** [influxdata/influxdb-client-js#337]
I'd expect `Point.toLineProtocol()` to be compatible with InfluxDB line protocol which needs to be in ns precision.

I'm trying to write line protocol points with Telegraf to influx db but the points are generated with ms precision like this:

```js
const point = new Point("some-measurement")
  .timestamp(1620838490826) // in milliseconds
  .floatField("value", 0.125)
```

So when I do `point.toLineProtocol()` I'd expect the output to be InfluxDB 2.0 compatible, right? That is writing the timestamp with ns precision.
Better, provide an option to choose the precision.

I see there's a [convertTime](https://influxdata.github.io/influxdb-client-js/influxdb-client.pointsettings.html) setting, but the documentation is really unclear.

More info here:
https://community.influxdata.com/t/telegraf-output-influxdb-v2-plugin-is-not-compatible-with-point-tolineprotocol-from-node-client/19860

**Comment by sranka** [comment]
Thank you for using the client and reporting an issue. 

The precision of the line protocol timestamp is given when writing the point

- https://influxdata.github.io/influxdb-client-js/influxdb-client.influxdb.getwriteapi.html
- https://docs.influxdata.com/influxdb/v2.0/api/#operation/PostWrite

WriteApi is constructed with the timestamp precision and the returned instance also properly implements `PointSettings` that you can pass to `toLineProtocol`.

The actual documentation is IMHO correct in https://influxdata.github.io/influxdb-client-js/influxdb-client.point.timestamp.html, any improvements that might further clarify it from your POV are welcome.

I have to admit that `toLineProtocol` should better assume `ns` precision when no `PointSettings` are supplied, it would certainly clarify the situation. Any such fixes would however not help with the issue that you describe - AFAIK, telegraf plugin requires line protocol with nanosecond precision, so you should better specify timestamp as 

```js
`${milis}000000`
```

**Comment by empz** [comment]
I understand but I still believe `toLineProtocol()` should emit timestamp in ns by default no matter how the `Point` was constructed in the first place.

I was going to attempt to write a PR for this but I see you beat me to it. Thank you!
