### ISSUE TITLE
Use Flux "package import" (interpolate.linear)

### ISSUE THREAD

**Issue by cantuket** [influxdata/influxdb-client-js#344]
__Proposal:__
If this is already possible then please advise, but I'd like to be able to use the ["interpolate.linear" function](https://github.com/influxdata/flux/blob/master/stdlib/interpolate/interpolate.flux) from queries using this library.

__Current behavior:__
Following the [Flux docs](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/interpolate/linear/) will generate an "unknown path" error.

__Desired behavior:__
Some workaround to use packages listed [here](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/), which require an "import" statement.

**Comment by sranka** [comment]
This client library does not manipulate the flux script that is sent to InfluxDB, it is the database that refused your script. In any case, you have to start your flux script with `import "interpolate"`. If you need more technical help regarding flux, feel free to ask the `flux` channel at https://influxcommunity.slack.com/ssb/redirect#/
