### ISSUE TITLE
What is the default timeout for the client?

### ISSUE THREAD

**Issue by chris-brown** [influxdata/influxdb-client-js#348]
We are getting timeouts but we are unable to tell how long the query takes before timing out. Can you help me understand if you dont provide a timeout what is the default?

https://influxdata.github.io/influxdb-client-js/influxdb-client.connectionoptions.html

I expected the default value to be documented above but wasnt.

Thanks

**Comment by sranka** [comment]
Thank you @chris-brown for reporting an issue. The default timeout is 10_000 milliseconds in node.js. The doc is now updated to inform about it.
