### ISSUE TITLE
Invalid tag format

### ISSUE THREAD

**Issue by dg-eparizzi** [influxdata/influxdb-client-js#352]
I'm building a `Point` object dynamically from an external input like this:

```ts
interface PointTag {
  name: string;
  value: string;
}

const point = new Point("some-measurement").timestamp(timestamp);

tags.forEach((tag: PointTag) => {
      if (tag.value) {
        point.tag(tag.name, tag.value);
      }
    });
```
So as you can see, I'm using the SDK `tag` method to add tags to the point.

__Expected Behavior:__
I'd expect this not to throw an error and automatically escape any conflicting characters.

__Current Behavior:__

It seems to be escaping characters incorrectly and throwing the following error.

```
ERROR: Write to InfluxDB failed. d [HttpError]: unable to parse 'traces,Application=Doosan\ GridTech\ Asset\ Controller,SourceContext=Microsoft.Hosting.Lifetime,contentRoot=C:\Program\ Files\Doosan\ GridTech\AssetController\,envName=Production,level=Information message="Application started. Hosting environment: \"Production\"; Content root path: \"C:\\Program Files\\Doosan GridTech\\AssetController\\\"" 1627994643411': invalid tag format
at IncomingMessage.<anonymous> (/app/node_modules/@influxdata/influxdb-client/dist/index.js:16:10167)
at IncomingMessage.emit (events.js:387:35)
at endReadableNT (internal/streams/readable.js:1317:12)
at processTicksAndRejections (internal/process/task_queues.js:82:21) 

{
  statusCode: 400,
  statusMessage: 'Bad Request',
  body: `{"code":"invalid","message":"unable to parse 'traces,Application=Doosan\\\\ GridTech\\\\ Asset\\\\ Controller,SourceContext=Microsoft.Hosting.Lifetime,contentRoot=C:\\\\Program\\\\ Files\\\\Doosan\\\\ GridTech\\\\AssetController\\\\,envName=Production,level=Information message=\\"Application started. Hosting environment: \\\\\\"Production\\\\\\"; Content root path: \\\\\\"C:\\\\\\\\Program Files\\\\\\\\Doosan GridTech\\\\\\\\AssetController\\\\\\\\\\\\\\"\\" 1627994643411': invalid tag format"}`,
  contentType: 'application/json; charset=utf-8',
  json: {
    code: 'invalid',
    message: `unable to parse 'traces,Application=My\\ App\\ Name\\ 
      Controller,SourceContext=Microsoft.Hosting.Lifetime,contentRoot=C:\\Program\\ Files\\Company\\ 
      Company\\Product\\,envName=Production,level=Information message="Application started. Hosting environment: 
      \\"Production\\"; Content root path: \\"C:\\\\Program Files\\\\Company\\\\Product\\\\\\"" 1627994643411': invalid 
      tag format`
  },
  code: 'invalid',
  _retryAfter: 0
}
```

- Version: 1.15.0
- Platform: Linux

**Comment by sranka** [comment]
Thank you @dg-eparizzi for posting an issue, it seems to be an encoding issue. Can you please also attach also JSON with original tag names and values?

**Comment by sranka** [comment]
InfluxDB does not support tag keys/values that end with `\` (backslash). There is no fix that the client library can possibly provide, a trailing backslash cannot be escaped. @dg-eparizzi Please consider **contentRoot**  being a point value rather than a tag, or remove the trailing backslash from the `contentRoot` value.

The root cause in https://github.com/influxdata/influxdb/blob/master/models/points.go#L760, a space separator between tags and fields is ignored and the point parser fails on `invalid tag format` after is reaches unescaped `=` in a value   

I was also able to reproduce this issue using a simple JS code

```js
// write point with the current (client-side) timestamp
const point1 = new Point('invalidTag')
  .tag('a', 'whatever\\')
  .floatField('value', 1)
writeApi.writePoint(point1)
console.log(point1.toLineProtocol(writeApi))
``` 
The actual influxdb protocol line is then

```
invalidTag,a=whatever\ value=1 1628062041142589524
```

**Comment by dg-eparizzi** [comment]
I don't have control over the incoming JSON and setting `contentRoot` as a field instead of a tag is not really an option.

Are there any problems with forward slashes? Do they need to be escaped? If I replace all `\` by `/` in all tag values, would that fix it?

Going to test that out right now.

**Comment by sranka** [comment]
There are no problems with forward slashes, it works fine.
