### ISSUE TITLE
Clarify use of url configured in env.js vs. env_browser.js

### ISSUE THREAD

**Issue by jstirnaman** [influxdata/influxdb-client-js#354]
__Expected Behavior:__

Please clarify in examples/README.md the need for configuring `url` in examples/env.js vs examples/env_browser.js when
running the browser example. Why configure `url` in two places?

__Current Behavior:__

The comment above `url` in examples/env_browser.js is unclear.

**Comment by sranka** [comment]
There is no simple way for a configuration to be shared between browser (index.html, giraffe.html) and node (the rest) examples. The examples also intentionally use different ways of how to import and use the client: with pure node.js javascript code; browser module javascript (index.html); browser script (giraffe.html); standard typescript; deno typescript.

Browser and node are different execution environments, examples/README.md also provides instructions to use different env.js files depending on environment.
