### ISSUE TITLE
Add Deno library to https://deno.land/x

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb-client-js#363]
see the instructions here: https://deno.land/x#info

We should add our Deno compatible library there so users can find it easily.

**Comment by sranka** [comment]
I configured this github repo to notify deno.land about new releases, a new release (1.17.0) was done to make this lib appear therein.

It is now easy to find :
 - https://deno.land/x?query=influxdb
 - https://deno.land/x/influxdb_client

**Comment by russorat** [comment]
Thanks! Could you update the readme and/or the examples for using deno.land in the import?

for example, i tried using 

```
import { Point } from 'https://deno.land/x/influxdb_client/packages/core/src/index.ts'
```

but got the following error:

```
deno run --unstable --allow-read --allow-write ./iss/postprocess.js -v
Download https://deno.land/x/influxdb_client/packages/core/src/index.ts
Warning Implicitly using latest version (v1.17.0) for https://deno.land/x/influxdb_client/packages/core/src/index.ts
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/index.ts
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/WriteApi
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/util/escape
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/util/currentTime
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/options
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/query
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/results
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/transport
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/Point
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/InfluxDB
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/QueryApi
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/errors
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/util/logger
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/observable
error: Import 'https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/WriteApi' failed: 404 Not Found
    at https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/index.ts:41:0
```

if i try it with `import { Point } from 'https://deno.land/x/influxdb_client/packages/core/src/Point.ts'` i get the following error:
```
deno run --unstable --allow-read --allow-write ./iss/postprocess.js -v
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/util/escape
Download https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/util/currentTime
error: Import 'https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/util/escape' failed: 404 Not Found
    at https://deno.land/x/influxdb_client@v1.17.0/packages/core/src/Point.ts:2:0
```

**Comment by sranka** [comment]
@russorat - import from `https://deno.land/x/influxdb_client/packages/core/src/index.ts` is not possible, the client sources are pre-processed to work fine in all supported environments (node.js, browser, deno). The deno client distributions would have to be persisted in git for such import to work fine, I'd better avoid persisting distributions in git. The existing sources can be hardly changed to work in deno OOTB and still support other platforms and an existing build pipeline.

Anyway, the main Readme currently points to a working deno example as well as examples/Readme does:

![image](https://user-images.githubusercontent.com/16321466/130822225-22a8d775-3465-48b5-b9ff-66539e929918.png)

The `query.deno.ts` example then shows the required deno networking flag and a valid import URL (for any public npm module). 
```js
#!/usr/bin/env -S deno run --allow-net
//////////////////////////////////////////////////////
// A modified query.ts example that works with deno //
//////////////////////////////////////////////////////

import {
  FluxTableMetaData,
  InfluxDB,
} from 'https://cdn.skypack.dev/@influxdata/influxdb-client-browser?dts'
```

**Comment by russorat** [comment]
> re: The deno client distributions would have to be persisted in git for such import to work fine, I'd better avoid persisting distributions in git

just for clarification, I don't see other libraries requiring the distributions to be stored in git to work. for example: https://deno.land/x/flat@0.0.13

is that just because our client lib supports multiple execution types?
