### ISSUE TITLE
No exposed api for disabling TLS verification

### ISSUE THREAD

**Issue by rockstar** [influxdata/influxdb-client-js#367]
There is a request in influxdata/vsflux#202 to allow vsflux to disable TLS verification. This can't be addressed until the apis (query, tasks, buckets, etc) have a method for disabling that verification.

**Comment by sranka** [comment]
You can turn off certificate verification using `rejectUnauthorized: false` in transport options passed to InfluxDB constructor. 
```js
const queryApi = new InfluxDB({
  url,
  token,
  transportOptions: {rejectUnauthorized: false},
}).getQueryApi(org)
```
The client allows to set extra [transportOptions](https://influxdata.github.io/influxdb-client-js/influxdb-client.connectionoptions.html) that are added to the underlaying [http.request](https://nodejs.org/api/http.html#http_http_request_options_callback) or
 [https.request](https://nodejs.org/api/https.html#https_https_request_options_callback) options in node.js.
I improved the docs in #368 to make it clear.

**Comment by Apollon77** [comment]
Ok, I checked it: InfliuzxDB 1.x not possible because we use old lib and upgrade is not planned.

For InfluxDB 2.x we can implement it
