### ISSUE TITLE
Protect against NaNs and Infinity in number-based fields

### ISSUE THREAD

**Issue by beheh** [influxdata/influxdb-client-js#369]
__Expected Behavior:__

When (accidentally) calling `.floatField`, `.intField` or `.uintField` with a value of `Infinity` or `NaN`, the library should raise an error that these values cannot be captured in Influx, or silently drop the fields.

__Current Behavior:__

When calling `.floatField` (and presumably also `.intField` or `.uintField`) with a value of `Infinity` or `NaN`, the library silently serializes the value to a literal Infinity or NaN in the line protocol, causing a remote Influx instance to drop the point due to malformed values.

__Possible Solution:__

While these methods do check for NaN, they only do so the value is not typeof number. As NaN and Infinity are both typeof number the check is bypassed.

The methods should probably explictly check the value using `isFinite` (which will return true only for non-Infinity and non-NaN values).

__Steps/Code to Reproduce the Problem:__

1. Create a new point
2. Set a field to Infinity or NaN
3. Send to Influx, and observe the dropped point in the server logs due to a malformed value (`error="unable to parse '<line>': invalid number"`)

```node
let point = new Point("my_measurement")
point.floatField("i", 1 / 0);
point.floatField("n", 1 + undefined);
point.toLineProtocol(); // 'my_measurement i=Infinity,n=NaN 1633083967087850200'
```

__Specifications:__

- Version: @influxdata/influxdb-client@v1.18.0, Influx at v1.8.9
- Platform: Windows / Linux

**Comment by sranka** [comment]
Thank you @beheh for using the client and posting this issue. I am on it shortly.
