### ISSUE TITLE
ScriptsAPI.postScriptsIDInvoke should have the same api as QueryAPI.queryRows

### ISSUE THREAD

**Issue by rockstar** [influxdata/influxdb-client-js#378]
With the release of 1.20, the `ScriptsAPI` is officially supported. The [documentation for `ScriptsAPI.postScriptsIDInvoke`](https://influxdata.github.io/influxdb-client-js/influxdb-client-apis.scriptsapi.postscriptsidinvoke.html) should return a similar api to [`QueryAPI.queryRows`](https://influxdata.github.io/influxdb-client-js/influxdb-client.queryapi.queryrows.html), as the amount of data coming out of the response is potentially big. In fact, the [documentation for `QueryAPI.queryRaw`](https://influxdata.github.io/influxdb-client-js/influxdb-client.queryapi.queryraw.html) specifically calls out this potential issue by saying "Use with caution, a possibly huge stream is copied to memory."

I understand that the clients are generated based on the Swagger doc, but this likely needs a custom implementation of some sort.

**Comment by sranka** [comment]
Thank you @rockstar for posting an issue. Sure, the openapi documentation of `ScriptsAPI.postScriptsIDInvoke` is too abstract to know what can be passed in and what is an expected response. https://docs.influxdata.com/influxdb/cloud/api-guide/api-invocable-scripts/ shows some handy examples of script execution of a `flux` script type. Can you please confirm that the `flux` script invocation response is always an annotated CSV stream? 

Yes, the solution herein is then a new custom `FluxScriptInvocationAPI` with methods similar to the existing `QueryApi`.
