### ISSUE TITLE
Duration literal to DateTime converter

### ISSUE THREAD

**Issue by dg-eparizzi** [influxdata/influxdb-client-js#379]
__Proposal:__
I'd like the library to expose a method that will convert a [duration literal](https://docs.influxdata.com/flux/v0.x/spec/lexical-elements/#duration-literals) to a DateTime.

__Use case:__
I want to automatically generate a reasonable time window depending on the timespan between range's start and stop timestamps on my API to avoid clients from requesting too much data (like 1s granularity for a whole year). Much just like what the InfluxDB 2.0 UI does.

There doesn't seem to be anything in the library that will do that. I know there's the `duration()` function in flux but I think it would be cumbersome to add that logic in a flux query.

**Comment by sranka** [comment]
Thank you @dg-eparizzi for posting an issue and your interest in this client library. I am not sure that I understand your use case. You can utilize the moment.js library to calculate what you need, it is IMHO quite simple to achieve. Can you please provide an example of a flux query and point to a place where such a requested library function should fit in?

**Comment by dg-eparizzi** [comment]
> Thank you @dg-eparizzi for posting an issue and your interest in this client library. I am not sure that I understand your use case. You can utilize the moment.js library to calculate what you need, it is IMHO quite simple to achieve. Can you please provide an example of a flux query and point to a place where such a requested library function should fit in?

Let's say I have an API that queries InfluxDB in the background and returns the data. 
Let's say the endpoint looks like (simplified) `/api?from={fromDuration}&to={toDuration}`

Now, the API needs to calculate the time range between `from` and `to` before sending the query. Depending on the time range between `from` and `to`, the API will generate the flux query with a smaller or bigger `window` (i.e. if the client asks for `from=-1y` and `to=now`, we will use a window of `6h`. If they simply ask for the past hour, we can do `10s`.

As far as I know, moment can't parse InfluxDB durations: `moment.duration("-1d")` doesn't work. I'd need to do some regex and/or parsing myself in order to be able to pass that into moment, which is exactly what I'm suggesting this library should provide.

**Comment by sranka** [comment]
Thank you for the explanation, I understand your point of view now. The trouble comes with the fact that the [flux duration literal](https://docs.influxdata.com/flux/v0.x/spec/lexical-elements/#duration-literals) is not standard. I understand that it is a complication. 

As a workaround, you can make your API accept standard duration literals (parseable by moment.js such as `-P1D`), compute precise dates for the range operator with the help of `moment.js`, and specify window in milliseconds. If this does not fit your needs, you are welcome to contribute with a function that creates an ISO8601 duration literal (parseable by moment.js) out of an influx duration literal. Are you willing to make a contribution herein?
