### ISSUE TITLE
when creating InfluxDB with timeout field which equals to undefined - throws unhandledPromiseRejection

### ISSUE THREAD

**Issue by yitzchak-ben-ezra-ecoplant** [influxdata/influxdb-client-js#380]
__Expected Behavior:__ when `timeout` is `undefined` or `null` - use default timeout definition (10000), or at least throw a catchable error!

__Current Behavior:__ I'm getting a connection reset without the ability to catch and handle it (except for a global unhandled promise rejection handler)

```
uncaughtException: socket hang up
Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

__Possible Solution:__

__Steps/Code to Reproduce the Problem:__

1. this code helped to workaround the issue:
```
const influxDb = new InfluxDB(timeout != null ? { ...clientOptions, timeout } : clientOptions);
```
code that causes the issue:
```
class InitConnectionParamsDto {
  url: string;
  token: string;
  org: string;
  timeout?: number | undefined;
  writeOptions?: Partial<WriteOptions>;
}
function getClient(options: InitConnectionParamsDto) {
  const { org, url, token, timeout, writeOptions } = options;
  return new InfluxDB({ url, token, timeout });
}
const client = getClient({url: '...', token: '...'})
```
2. use that client to write data

__Specifications:__

- Version: tested on 1.15.0 to 1.20.0
- Platform: Nodejs 14, alpine

**Comment by sranka** [comment]
Thank you @yitzchak-ben-ezra-ecoplant for using the client and posting an issue. Setting up timeout to `undefined` generally means that there is no timeout on the client side. This fact might require a better explanation in the code/docs.
A situation with a communication error that is not properly propagated to the client code is a bug to fix.

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
Fixing the propagation will be very helpful. thank you for that.

as for the timeout - I think this is the difference between an explicit `null` to an explicit `undefined`.
an explicit `null` or `0` means no timeout defined. but `undefined` in my honest opinion means that you should use the default value. do whatever you think is right.. just said here what I think about it.

**Comment by sranka** [comment]
I was able to reproduce the situation with a closed connection (by the server), the client however propagates the error properly with the stack trace that is exactly the same that you provided. I also went through [the code](https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/impl/node/NodeHttpTransport.ts) and [node documentation](https://nodejs.org/api/http.html#httprequesturl-options-callback) and everything looks fine from the client POV. Are you sure that an unhandled error is caused by the client library? I can achieve an unhandled promise rejection if I don't catch the promise returned by `writeApi.close()` or `writeApi.flush()`.

These are my steps, all executed from the root of this git repository.

__Generate certificate__
```
cd examples/scripts
openssl genrsa -out key.pem
openssl req -new -key key.pem -out csr.pem
openssl x509 -req -days 9999 -in csr.pem -signkey key.pem -out cert.pem
rm csr.pem
```
__Create examples/scripts/server2.js__
```js
const express = require('express')
const fs = require('fs')

const port = 8086
const timeout = 1000

const app = express()
app.all('/api/v2/query', async (req, resp) => {
  console.log(req.path)
  setTimeout(() => {
    resp.status(200)
    resp.end()
  }, timeout + 1000)
})

const options = {
  key: fs.readFileSync('key.pem', 'utf8'),
  cert: fs.readFileSync('cert.pem', 'utf8'),
}

const server = require('https').createServer(options, app)
server
  .listen(port, () => {
    console.log(`listening on https://localhost:${port}`)
  })
  .setTimeout(timeout)
```
__Start server2.js in a new terminal__
```bash
cd examples/scripts
node server2.js 
```

__Execute query example__
```bash
export INFLUX_URL=https://localhost:8086
export NODE_TLS_REJECT_UNAUTHORIZED=0
node --unhandled-rejections=strict examples/write.js
```

output:
```
*** WRITE POINTS ***
 temperature,example=write.ts value=29 1636488751331525234
 temperature,example=write.ts,location=pzavora-nb value=11.4 1636488751332000000
(node:25388) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
WARN: Write to InfluxDB failed (attempt: 1). Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET'
}
ERROR: Retry buffer closed with 2 items that were not written to InfluxDB! 
Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET'
}

Finished ERROR
```

`Finished ERROR` herein clearly indicates that an error was caught properly.

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
Thanks @sranka , I can test it tomorrow but it's look like you didn't used the options as I described
in `write.js` line 12 add a `timeout` option - and set it to `undefined`
like this:
`const writeApi = new InfluxDB({url, token, timeout: undefined}).getWriteApi(org, bucket, 'ns')`

Then it'll throw without proper propagation
I'll try to test it tomorrow

**Comment by sranka** [comment]
I didn't use your options because the fake server closes the connection after 1 second. It could have been set to undefined with the same result.

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
Tested now - I tried without `timeout` set to `undefined` and got result like yours

I then added the `timeout` parameter and voila:

```
*** WRITE POINTS ***
 temperature,example=write.ts value=28.8 1636526898204425500
 temperature,example=write.ts,location=DESKTOP-KRDD6HJ value=19.2 1636526898205000000
(node:1671) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling ce
rtificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
internal/process/promises.js:213
        triggerUncaughtException(err, true /* fromPromise */);
        ^

TypeError [ERR_INVALID_ARG_TYPE]: The "msecs" argument must be of type number. Received undefined
    at validateNumber (internal/validators.js:129:11)
    at getTimerDuration (internal/timers.js:381:3)
    at ClientRequest.setTimeout (_http_client.js:858:11)
    at at._request (/mnt/c/gitWorkspace/Open_Source/influxdb-client-js/packages/core/dist/index.js:16:10687)
    at /mnt/c/gitWorkspace/Open_Source/influxdb-client-js/packages/core/dist/index.js:16:8331
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

no `Finished ERROR` here - and you can see `triggerUncaughtException` in the output

**Comment by sranka** [comment]
I see, the actual exception is fired from node.js as a result of a validation of the `timestamp` settings.
