### ISSUE TITLE
Provide a way to flush and/or delete some data on the database

### ISSUE THREAD

**Issue by anthonyrovira** [influxdata/influxdb-client-js#384]
__Proposal:__
I could be wrong but I don't see any way to flush the database or to simply delete some data on the database by this package.
I noticed that it is still possible using [Influx CLI ](https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/delete/) but would be very handy to make it by code.

__Current behavior:__
Didn't find another way than by the CLI...

__Desired behavior:__
Implement the method 'deleteAPI(org: string, bucket: string)' or similar in the InfluxDB class.

__Alternatives considered:__
Alternatively, provide a way to query it maybe...

__Use case:__
In my opinion, every modern database needs to be flushed by something else than the CLI

**Comment by sranka** [comment]
Thank you @anthonyrovira for using the client and posting an issue. The client is split into [2 main packages](https://github.com/influxdata/influxdb-client-js#features). All management APIs are described in https://influxdata.github.io/influxdb-client-js/influxdb-client-apis.html. The same APIs are also used by Influx CLI. You are probably looking for this:

```js
import {InfluxDB} from '@influxdata/influxdb-client'
import {DeleteAPI} from '@influxdata/influxdb-client-apis'
const influxDB = new InfluxDB({url: 'http://localhost:8086', token: 'my-token'})

async function deleteData() {
  const deleteAPI = new DeleteAPI(influxDB)
  await deleteAPI.postDelete({
    org: 'my-org',
    bucket: 'my-bucket',
    // you can better specify orgID, bucketID if you have them in your code
    body: {
      start: new Date(Date.now() - 60 * 1000).toISOString(),
      stop: new Date().toISOString(),
      predicate: '_measurement="temperature"',
    },
  })
}

deleteData()
  .then(() => console.log('\nFinished SUCCESS'))
  .catch(error => {
    console.error(error)
    console.log('\nFinished ERROR')
  })
```
The [examples/createBucket.js](https://github.com/influxdata/influxdb-client-js/blob/master/examples/createBucket.js) also shows how to delete a bucket.
