### ISSUE TITLE
getDeleteApi()

### ISSUE THREAD

**Issue by Koorae** [influxdata/influxdb-client-js#389]
__Proposal:__
Similar to getQueryApi() and getWriteApi(). It would be great if there is also a getDeleteApi().

Right now, I am writing some test cases since the application uses influx's write and query. However, going forward, I need to occasionally delete rows of data and also always wipe the database after testing. Therefore, it would be very helpful if there is somehow a way to delete data in a similar fashion as query and write. 

Please let me know if there are any development on this or some suggested alternatives for this. Thank you!

**Comment by sranka** [comment]
Thank you for using the client and opening an issue. I'll have to improve the doc make sure the DeleteAPI is included in `@influxdata/influxdb-client-apis`. For an example, see https://github.com/influxdata/influxdb-client-js/issues/384#issuecomment-968345547

**Comment by sranka** [comment]
You can also delete/recreate buckets to perform a complete cleanup,  see [examples/createBucket.js](https://github.com/influxdata/influxdb-client-js/blob/master/examples/createBucket.js).

**Comment by sranka** [comment]
Note that the delete functionality is intentionally not part of the core API. The delete operation is not smth that should happen frequently in InfluxDB, the written data are internally managed in immutable files. The delete operation creates a tombstone entry (in another file) to record deleted series keys/time ranges.
