### ISSUE TITLE
Reusing connections

### ISSUE THREAD

**Issue by xjohnp00** [influxdata/influxdb-client-js#393]
Hi,
Is there a way to reuse the connection and still flush the buffer (using JavaScript on AWS)? I tried to provide a custom connection header (Connection: Keep-Alive) and it did not work. The connection was closed anyway (I tested this on local InfluxDB 2.0.8 in docker). Does this behavior differ between InfluxDB OSS and Cloud?
I am currently creating the instance of write api like this
```typescript
const writeApi = this.client.getWriteApi(this.org, this._bucket, "s");
```
And flushing written points using
```typescript
writeApi.flush();
```
I tried providing `Connection: Keep-Alive` header by passing my `WriteOptions` to `InfluxDB.getWriteApi()`
Thanks.

**Comment by sranka** [comment]
Thank you @xjohnp00 for using the client and posting an issue. Node.js HTTP client OOTB does not reuse connections, you can change the default with a help of an [Agent](https://nodejs.org/api/http.html#class-httpagent). Your client code would then look like this:

```js
const {Agent} = require('http')
...
const agent = new Agent({
  keepAlive: true,
  keepAliveMsecs: 20 * 1000, // 20 seconds keep alive
})
const writeApi = new InfluxDB({
  url,
  token,
  transportOptions: {agent},
}).getWriteApi(org, bucket, 'ns')
...
```

There is no need to specify the `Connection` header, the agent will do it. I double-checked it with a modified [write.js example](https://github.com/influxdata/influxdb-client-js/blob/master/examples/write.js) and a fake HTTP server:
```
const express = require('express')
const port = 8086
const app = express()
app.post('/api/v2/write', (req, resp) => {
  console.log(req.path, req.headers)
  resp.sendStatus(204)
})
app.listen(port, () => {
  console.log(`listening on http://localhost:${port}`)
})
```

**Comment by xjohnp00** [comment]
Great, works flawlessly.
Thanks.
