### ISSUE TITLE
Query language options

### ISSUE THREAD

**Issue by JorgosCoenen** [influxdata/influxdb-client-js#397]
I'm trying to use the JS client but struggling with the flux query language... 
I see that QueryOptions has a "type" property according to the documentation, but I can't seem to find what it accepts other than flux. 
I'm particularly hoping to use SQL, such as in Grafana or the influx CLI. 

__Proposal:__
Supporting SQL in the query api.

__Current behavior:__
Unclear if anything other than flux is supported.

__Use case:__
More accessible to users coming from other db and query environments.

**Comment by sranka** [comment]
Hi Jorgos, InfluxDB v2 primary query language is flux, there is no other language available in the v2 API (and this client library), it has to be `flux`. InfluxDB also supports InfluxQL, which is closer to SQL ... but it requires extra configuration steps (https://docs.influxdata.com/influxdb/v2.1/query-data/influxql/) to map v2 buckets to v1 databases. The v1 javascript client library is https://github.com/node-influx/node-influx .
