### ISSUE TITLE
Rename `IPrefixed` interfaces?

### ISSUE THREAD

**Issue by chnn** [influxdata/influxdb-client-js#41]
What do you think about renaming all the `I` prefixed interfaces to something more suggestive of what they do? e.g. `IDashboard` to `DashboardWithLabels` or something.

It seems like:

- It's confusing to have two similarly named interfaces with no indication of which should be used (`IDashboard` and `Dashboard`)
- Ideally the project would only export one `Dashboard` type
- The `I` prefix is a rare stylistic choice among TypeScript projects, and it's rarity makes for an awkward public API. Prefixing types with an `I` is meant to separate interfaces and implementations—but we don't have implementations of the interfaces in this library

**Comment by bednar** [comment]
This client library was replaced with new version, so this issue is outdated.
