### ISSUE TITLE
Documentation shows "auth" as required field in postUsersIDPassword

### ISSUE THREAD

**Issue by theGOTOguy** [influxdata/influxdb-client-js#410]
__Expected Behavior:__

Documentation should show that the `auth` field of `UsersAPI.postUsersIDPassword` is optional, because

```node
   await usersAPI.postUsersIDPassword({
        userID: user.influxId,
        body: {password: newPassword}
    });
```

works if we are using the Influx admin token.

__Current Behavior:__

[Documentation shows the `auth` field of `UsersAPI.postUsersIDPassword` is required.](https://influxdata.github.io/influxdb-client-js/influxdb-client-apis.postusersidpasswordrequest.html)

__Possible Solution:__

Update documentation to show `auth?` instead of `auth`.

__Steps/Code to Reproduce the Problem:__

1)  Start InfluxDB in a Docker container.
2)  Create a user.
3)  Update the user's password using `usersAPI.postUsersIDPassword` when using the admin token in your Influx session.  Note that `auth` field is not required.

__Specifications:__

- Version:  1.21.0
- Platform:  Ubuntu 21.10

**Comment by theGOTOguy** [comment]
Maybe the right answer is to close this bug and to file one against influxdata/openapi, so that it can be fixed upstream?

Let me know what you prefer.  If so, I will file against influxdata/openapi.

**Comment by sranka** [comment]
Thank you for your POV, I went through similar thoughts. The InfluxDB swagger uses BasicAuthentication to express that it can be additionally used to the global authentication schemes (token or session). A change in the client API is required to respect it. The other question is whether the InfluxDB openapi spec itself requires better specification of authentication requirements ... I don't think so.

**Comment by theGOTOguy** [comment]
Thank you, @sranka
