### ISSUE TITLE
how to query data as kline(1m,5m,1h)?

### ISSUE THREAD

**Issue by cheungchingli** [influxdata/influxdb-client-js#428]
__Proposal:__
Short summary of the feature.

__Current behavior:__
Describe what currently happens.

__Desired behavior:__
Describe what you want.

__Alternatives considered:__
Describe other solutions or features you considered.

__Use case:__
Why is this important (helps with prioritizing requests)?

**Comment by sranka** [comment]
Feel free to ask specific questions about `flux` queries/scripts at https://community.influxdata.com/ .
