### ISSUE TITLE
Cookies omitted from request

### ISSUE THREAD

**Issue by dimitrisfasoulas** [influxdata/influxdb-client-js#446]
__Expected Behavior:__
A request from a site that has a cookie set should go out with said cookie

__Current Behavior:__
Fetch requests are send without cookies

__Possible Solution:__
I see that #160 changed fetch options so cookies are not sent by changing the `credentials ` option to `omit `from `include`.
https://github.com/influxdata/influxdb-client-js/blob/master/packages/core/src/impl/browser/FetchTransport.ts#L207

In a project I'm working on influx is behind a gateway that will redirect every request without a proper session cookie. The cookie exists but since fetch is setup like that, its omited from the request.

Is there a way to overwrite request options during `new InfluxDB()` or any other way to solve this ?

__Specifications:__

- Version: 1.24.0

**Comment by dimitrisfasoulas** [comment]
Wow that was fast !

I did try   `transportOptions `but as I saw it was not picked up for browser.

Thank you for the very fast reply

**Comment by sranka** [comment]
The `transportOptions` enhancement works fine since `@influxdata/influxdb-client-browser@1.26.0-nightly.2014`
