### ISSUE TITLE
WARN: Write to InfluxDB failed (attempt: 1). Error: read ECONNRESET

### ISSUE THREAD

**Issue by noob-master147** [influxdata/influxdb-client-js#454]
Influx error, not able to programmatically write data

![image](https://user-images.githubusercontent.com/43108912/172894391-c44939a5-39c3-4c4b-9a49-a7c8a365ad96.png)

in reply to https://github.com/influxdata/influxdb-client-js/issues/453#issuecomment-1151034521

OS : MacOS Monterey 12.2.1 (21D62) M1
Node version : v14.18.1
influxDB version : influxdb 2.2.0
influxDB cli version : 2.3.0
npm client version : "^1.26.0"

**Comment by sranka** [comment]
Can you pls share an excerpt of your code and estimate the count of written points?

**Comment by noob-master147** [comment]
earlier i was writing some 2000 points, then i tried to write single points as well but it still kept failing 
also it was working fine before when i was writing 20 - 50 points at a time, everything started to go south as soon as i was writing 2000 points and #453 started happening and now this 

i install influx using if that helps
`brew install influxbd && brew install influxdb-cli`

here is the code I'm using
```
async migrateActivityLogs() {
        try {
            const orgs = await Org.find({})
            const writeApi = client.getWriteApi(config.influx.org, 'activities', 'ms')
            for (let org of orgs) {
                console.log(chalk.yellow(`\n\nMigrating Activity Logs for ${org.name}`))
                const activities = await Activity.find({org: org._id})
                for(let activity of activities) {
                    const queryBuilderObject = {
                        measurement: 'activities',
                        timeStamp: moment(activity.createdAt).utc().valueOf(),
                        tags: {
                            org: activity.org.toString(),
                            action: activity.action.parent,
                            type: activity.action.child,
                        },
                        fields: {}
                    }
                    if (!queryBuilderObject.tags.action || !queryBuilderObject.tags.type) {
                        continue;
                    }
                    if (activity.user) queryBuilderObject.fields.user = activity.user.toString()
                    if (activity.org) queryBuilderObject.fields.org = activity.org.toString()
                    if (activity.service) queryBuilderObject.fields.service = activity.service.toString()
                    if (activity.incident) queryBuilderObject.fields.incident = activity.incident.toString()
                    if (activity.integration) queryBuilderObject.fields.integration = activity.integration.toString()

                    // console.log(queryBuilderObject)
                    const queryBuilder = new InfluxQueryBuilder(queryBuilderObject)
                    const point = queryBuilder.writeQuery()

                    console.log(point.toLineProtocol())
                    writeApi.writePoint(point)
                }
            }
            writeApi.close()
            .then(() => console.log('FINISHED'))
            .catch(e => console.error(e))


        } catch (error) {
            console.log(error)
            return error
        }
    }
```

**Comment by noob-master147** [comment]
can this be happening because of low memory on my machine ?
<img width="629" alt="image" src="https://user-images.githubusercontent.com/43108912/172921053-6a7beeab-b2d3-4617-a377-4cda485028c5.png">

i dont understand how 16gb of RAM could be chewed up so quick, this definitely wasn't the case before i started working with influx, could something be wrong with my configurations?

**Comment by sranka** [comment]
Please read https://github.com/influxdata/influxdb-client-js/issues/213#issuecomment-660251486 , the approach that you use is IMHO not good for importing the data. See also https://github.com/influxdata/influxdb-client-js/blob/master/examples/writeAdvanced.js .

I can't comment the server configuration issues. I don't think that this is cause by the cYou can however use influx-cli

**Comment by sranka** [comment]
I also improved [writeAdvanced.js](https://github.com/influxdata/influxdb-client-js/blob/50f00a9dd5ddc267b28a51131803cd37bd9b1638/examples/writeAdvanced.js) to demonstrate how to reuse TCP connections during data import, it might help. It works fine to me locally against InfluxDB 2.2.0 (dockerized on top of AMD64 linux / 16G RAM / IntelCore i7 6th gen), 10_000 points are imported in 200ms.

**Comment by noob-master147** [comment]
hey @sranka 

thanks for the improvement, also the method to migrate data using the .line file is relatively smooth, thanks for that. 

although i have some concerns with that way of migrating data, there seems to be a limit on the size of file that influx can take which is 10MB. **How do you propose to migrate data with over 2,000,000,000 lines, file size being 160MB**

**Comment by sranka** [comment]
Thank you @noob-master147 for letting me know. Feel free to ask [community ](https://community.influxdata.com/).
