### ISSUE TITLE
Contains() in flux query.

### ISSUE THREAD

**Issue by JorgosCoenen** [influxdata/influxdb-client-js#463]
Attempting to use the "contains()" function in a Flux query to filter out anything matching an array of values.

__Expected Behavior:__

Provide an array of values to the "contains()" function in the Flux filter.

__Current Behavior:__

Keep getting an error like for instance: 'unexpected token for property key: INT ("12")'.
The example in the documentation also seems to work with Strings, so not sure where the INT here comes from. I'm also comparing to a field that is a string. 

__Steps/Code to Reproduce the Problem:__

Array used to filter:
sessionsExclude = [  '100', '102', '103', '105', '106', '109', '110' ]

Flux query segment:
|> filter(fn:(r) => contains(value: r["session"], set: `+sessionsExclude+`))

**Comment by sranka** [comment]
The root cause is in the flux script itself, feel free to ask for help and share your case in a `flux` slack channel, see  https://community.influxdata.com/ for details of how to join Slack.
