### ISSUE TITLE
makefile: sed fails under linux

### ISSUE THREAD

**Issue by powersj** [influxdata/influxdb-client-js#568]
### Specifications

* Client Version: master
* InfluxDB Version: latest
* Platform: linux

### Code sample to reproduce problem

```javascript
null
```

### Expected behavior

Makefile completes sucessfully

### Actual behavior

Makefile fails with:

```
sed: can't read : No such file or directory
```

### Additional info

This is due to a difference between the `sed` used by Linux (GNU) and macOS (BSD). The -i behavior is different between the two.

Reference:

- https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux
- https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed
- https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux

**Comment by sranka** [comment]
Reproducible locally @ Ubuntu 22.04 . I'll change the `sed` line to run a simple node script ... it will be then platform neutral.
