### ISSUE TITLE
Issue running `yarn apidoc && yarn apidoc:gh-pages`

### ISSUE THREAD

**Issue by sspaink** [influxdata/influxdb-client-js#591]
Had to npm install multiple dev dependencies in order for this release step to work without error, listed here: https://github.com/influxdata/influxdb-client-js/commit/693703d1615354e8f608b08f35e16ed4316295f9 I accidentally commited these package.json changes but reverted them.

**Comment by sranka** [comment]
https://github.com/bonitoo-io/influxdata/blob/main/influxdb-clients/ReleaseCycleSettings.md#4-publish-a-new-documentation works for me, `make publish VERSION=1.30.1` installs the required dependencies using `yarn install --frozen-lockfile` into the top-level node_modules directory (as you did manually)

`yarn apidoc` runs fine to me locally, it is also a part CI test check in https://github.com/influxdata/influxdb-client-js/blob/master/.circleci/config.yml#L35. It could be some local problem in your installation (old yarn?), you shouldn't use `npm` anyway to install dependencies.

my local env:
- ubuntu 22.04
- node v16.14.0
- yarn 1.22.19

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
