### ISSUE TITLE
Switch builds/tests to node 18.x

### ISSUE THREAD

**Issue by sranka** [influxdata/influxdb-client-js#623]
### Specifications

* Client Version: ANY
* InfluxDB Version: ANY
* Platform: ANY

### Code sample to reproduce problem

```javascript
```

### Expected behavior

Test and builds runs with node 18, the current LTS version.  Updates are  required in circle ci config and readme files.

### Actual behavior

Tests and builds run with node 16, which is in maintenance since 2022-10-18.

**Comment by tkurki** [comment]
So there is no expected compatibility with Node versions that are still in active maintenance? 

I find that decision pretty odd. Certainly makes me rethink investing time & effort in InfluxDb. I am totally ok with not supporting old versions forever.

**Comment by sranka** [comment]
> So there is no expected compatibility with Node versions that are still in active maintenance?

@tkurki, the compatibility is expected, there should be no worries on your side ... yes, we should better keep tests on oldest lts version
