### ISSUE TITLE
keepAlive example does not match to the title/comment

### ISSUE THREAD

**Issue by mok-liee** [influxdata/influxdb-client-js#640]
hello,

i think the `keepAlive` prop should be `true`?!

https://github.com/influxdata/influxdb-client-js/blob/a53cc88e58a960e200dbeba08f31e09a6d9b345e/examples/writeAdvanced.mjs#L56

see here https://github.com/influxdata/influxdb-client-js/issues/393#issuecomment-985272866

**Comment by bednar** [comment]
Hi @mok-liee,

thanks for using our client.

You are right. Is this something you might be willing to help with?

Regards
