### ISSUE TITLE
Code examples are not clear on how to actually save the queried rows to a variable

### ISSUE THREAD

**Issue by Pistrie** [influxdata/influxdb-client-js#666]
### Specifications

* Client Version: 1.33.0
* InfluxDB Version: latest docker version
* Platform: Linux

### Code sample to reproduce problem

```javascript
function queryRows() {
  console.log('*** QueryRows ***')
  queryApi.queryRows(fluxQuery, {
    next: (row: string[], tableMeta: FluxTableMetaData) => {
      // the following line creates an object for each row
      const o = tableMeta.toObject(row)
      // console.log(JSON.stringify(o, null, 2))
      console.log(
        `${o._time} ${o._measurement} in '${o.location}' (${o.example}): ${o._field}=${o._value}`
      )
    },
    error: (error: Error) => {
      console.error(error)
      console.log('\nQueryRows ERROR')
    },
    complete: () => {
      console.log('\nQueryRows SUCCESS')
    },
  })
}
```

### Expected behavior

I expect a result that will show me how to return the queried rows to a variable when calling the function.

### Actual behavior

The example only show how to log the row to the console

**Comment by bednar** [comment]
Hi @Pistrie,

thanks for using our client.

> ### Expected behavior
> I expect a result that will show me how to return the queried rows to a variable when calling the function.

You can use [QueryApi.collectRows() method](https://influxdata.github.io/influxdb-client-js/influxdb-client.queryapi.collectrows.html) for this purpose.

Here is an example:

https://github.com/influxdata/influxdb-client-js/blob/2075d834f5acb689adbef0f22d9bafc894abfe02/examples/query.ts#L68

Regards

**Comment by Pistrie** [comment]
It works, thanks :)
