### ISSUE TITLE
How to integrate join queries in flux queries

### ISSUE THREAD

**Issue by ashanjayasundara** [influxdata/influxdb-client-js#699]
__Proposal:__
Update the documentation for multiple queries and merge result in InfluxDB. I am trying integrate this with referring to to following documentation but its unclear how to install sql and influx packages

**Comment by powersj** [comment]
Hi,

Can you provide an example of what you would like to see? I am curious if referring to the [flux documentation](https://docs.influxdata.com/flux/v0.x/join-data/) is a better solution that duplicated what is there.

Thanks!

**Comment by powersj** [comment]
Going to close for lack of inactivity. If there was something we can follow up let us know.
