### ISSUE TITLE
Creating new databases

### ISSUE THREAD

**Issue by JorgosCoenen** [influxdata/influxdb-client-js#705]
I could be misunderstanding, but is it not possible to create a new database using this package?

This is included in the 'node-influx' package, for example:
https://node-influx.github.io/class/src/index.js~InfluxDB.html#instance-method-createDatabase

Thanks!

**Comment by WilhelmStein** [comment]
@JorgosCoenen  Correct me if I am wrong, but I was under the impression that this library targets 2.x versions of influx, which do not have "databases". Versions 2.x  instead have "buckets", no?

**Comment by JorgosCoenen** [comment]
@WilhelmStein Ha, that's possible... I am using it successfully to query data from a 1.x version of influx however. 
Using the other package for now to create new databases, but obviously not ideal to require both.

**Comment by powersj** [comment]
WilhelmStein is correct. This library is meant for InfluxDB v2. It has some legacy support for the 1.x for write and query only when flux is enabled.

Other actions require the previous library: https://github.com/node-influx/node-influx
