### ISSUE TITLE
vite process env not define in vue3

### ISSUE THREAD

**Issue by xalteropsx** [influxdata/influxdb-client-js#720]
![image](https://user-images.githubusercontent.com/103671642/217107887-4a0f05a6-72bd-4292-b8d6-0c4f9bbc71dd.png) cause of error import {InfluxDB} from '@influxdata/influxdb-client'

**Comment by xalteropsx** [comment]
![image](https://user-images.githubusercontent.com/103671642/217108194-4fb19d21-ba5b-43eb-9759-85a5c6c77c3f.png)
when i define process.env 
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import tailwindcss from 'tailwindcss'
import autoprefixer from 'autoprefixer'
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
        css: {
        preprocessorOptions: {
          postcss: {
            plugins: [tailwindcss, autoprefixer],
          },
        },
      },
    define: {
    'process.env': {}
  }
})
```

**Comment by msc5** [comment]
Did you find a solution to this?

**Comment by Avarow** [comment]
I have the same issue
