### ISSUE TITLE
Pure Javascript Examples

### ISSUE THREAD

**Issue by maufc** [influxdata/influxdb-client-js#905]
Short summary of the feature.
I'd need flux queries examples in javascript, not ts.
Describe what currently happens.
*.mjs and *. ts examples only
Describe what you want.
Examples on how to query in pure javascript, not typescript.
Describe other solutions or features you considered.
Just translate the files to js
Why is this important (helps with prioritizing requests)?
For add the functionality to existing scripts in JS

Thanks!

**Comment by bednar** [comment]
Hi @maufc,

here is am example in pure JavaScript: https://github.com/influxdata/influxdb-client-js/blob/24fe4e47e3a9adeb04ce06ab1bb9c11bd9d59b45/examples/index.html#L75

Regards

**Comment by maufc** [comment]
Ok. Thanks.
I could find a very good example in the InfluxDB WebUI.
It calls the @influxdata/influxdb-client library.
Is it the same library, right?
Thanks!

**Comment by bednar** [comment]
> It calls the @influxdata/influxdb-client library.
Is it the same library, right?
Thanks!

Yes
