### ISSUE TITLE
[Bug Report] lost precision for nano second _time

### ISSUE THREAD

**Issue by emeryao** [influxdata/influxdb-client-js#906]
https://github.com/influxdata/influxdb-client-js/blob/24fe4e47e3a9adeb04ce06ab1bb9c11bd9d59b45/packages/core/src/results/FluxTableColumn.ts#L60C22-L60C22

This line of code converts a string to a number when the column is the `_time` field
when the `_time` is timestamp string of a nano second like `"1698305602883000011"` the convention loses some precision to a number `1698305602883000000`

---
Sorry for my poor English 😆

**Comment by emeryao** [comment]
as a workaround I tried the code below and it works for me now

```typescript
queryApi.collectRows(someFlux, (value, meta) => {
  const nanoSecTime: string = values[meta.column('_time').index];
});
```

**Comment by bednar** [comment]
Hi @emeryao,

thanks for using our client and report this defect.

We will take a look.

Regards

**Comment by emeryao** [comment]
Additional info

```typescript
queryApi.collectRows(someFlux, (value, meta) => {
  console.log(values);
  // output:
  // [
  //   '',
  //   '10',
  //   '2023-10-27T07:10:30.862780217Z',
  //   '2023-10-27T07:30:30.862780217Z',
  //   '2023-10-27T07:17:55Z',
  //   '2023-10-27T15:10',
  //   'field_name',
  //   'measurement_name'
  // ] 

  console.log(meta.column('_time').index);
  // output: 4
});
```

**Originally** the `_time` field defaults to a string in ISO format like `"2023-10-27T07:17:55Z"` in the above codes which does not contains nano seconds
but in my project I want to fetch the nano second `_time` fields so I add a `map` statement in the flux query below

```flux
from(bucket: "bucket_name")
  |> range(start: -10m)
  |> filter(fn: (r) => r["_measurement"] == "measurement_name")
  |> map(fn: (r) => ({r with _time: uint(v: r._time)}))
```

with this flux query the `_time` field become a nano second timestamp string like `"1698305602883000011"` and the issue happens here

---
Sorry for the late info 😅

**Comment by emeryao** [comment]
the overall spot is that I want to get the `_time` field in nano seconds precision in the returned data
all the tricks I have done is trying to achieve that 😅 

Maybe there are some other ways to fullfill my needs if so please help

**Comment by sranka** [comment]
@emeryao a javascript number is a 64-bit floating point (double), the maximum integer value it can carry without loosing precision is [9007199254740991](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) . The present-days nanosecond time is much higher, a nanosecond precision is thus always lost when converting to a js Number. 

You can customize the way of how `unsignedLong` string values are converted by this client with the following initialization code:
```ts
import {typeSerializers} from '@influxdata/influxdb-client'
...
typeSerializers['unsignedLong'] = (x) => BigInt(x) // use BigInt, it does not loose precision
typeSerializers['unsignedLong'] = (x) => x // keep it as a string value
```

**Comment by emeryao** [comment]
thanks for your reply @sranka 👍 

hear `typeSerializers` for the first time and will give it a try 😄
