### ISSUE TITLE
How to use packages like "boundaries.week()"

### ISSUE THREAD

**Issue by larzknoke** [influxdata/influxdb-client-js#918]
Is it possible to import packages like `boundaries.week()` to use it in queries for `@influxdata/influxdb-client`?

[https://docs.influxdata.com/flux/v0/stdlib/date/boundaries/week/](https://docs.influxdata.com/flux/v0/stdlib/date/boundaries/week/)

**Comment by bednar** [comment]
Hi @larzknoke,

Thank you for using our client.

To resolve your issue, please update your query to include an import of the `boundaries` package.

Best regards

**Comment by larzknoke** [comment]
thanks for the quick respond. Can you give me an example of what the query should look like here?

**Comment by bednar** [comment]
```
import "date/boundaries"

lastWeek = boundaries.week(week_offset: -1)

from(bucket: "example-bucket")
    |> range(start: lastWeek.start, stop: lastWeek.stop)
```
