### ISSUE TITLE
WriteRecord() doesn't insert json

### ISSUE THREAD

**Issue by namish34531** [influxdata/influxdb-client-js#921]
### Specifications

* Client Version:1.8.0
* InfluxDB Version:
* Platform:node.js

### Code sample to reproduce problem

```let writeClient = client.getWriteApi(org,bucket, 'ns');
const line2={ measurement: "piano", tags: { app: "mq" }, fields: { uname: "john" } };

writeClient.writeRecord(line2);
writeClient.close().then(() => {
  console.log('WRITE FINISHED')
})
```

### Expected behavior

I want to insert this data

### Actual behavior

It's giving me error.
Can't I insert data in this format,actually I'm taking input in my project in this form

**Comment by bednar** [comment]
Hi @namish34531,

thanks for using our client.

The `writeRecord` should be used for writing the [LineProtocol](https://docs.influxdata.com/influxdb/v2/reference/syntax/line-protocol/). You have to transform your into LineProtocol or to `Point` data structure and then use the `writePoint` function.

Regards
